// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/expression/additive_expression.h"

void AdditiveExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AdditiveExpression1" << std::endl;
    multiplicativeExpressionAst1->Dump(depth + 1);
}

AdditiveExpression1::~AdditiveExpression1() {
    delete multiplicativeExpressionAst1;
}

void AdditiveExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AdditiveExpression2" << std::endl;
    additiveExpressionAst1->Dump(depth + 1);
    addAst2->Dump(depth + 1);
    multiplicativeExpressionAst3->Dump(depth + 1);
}

AdditiveExpression2::~AdditiveExpression2() {
    delete additiveExpressionAst1;
    delete addAst2;
    delete multiplicativeExpressionAst3;
}

void AdditiveExpression3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AdditiveExpression3" << std::endl;
    additiveExpressionAst1->Dump(depth + 1);
    subAst2->Dump(depth + 1);
    multiplicativeExpressionAst3->Dump(depth + 1);
}

AdditiveExpression3::~AdditiveExpression3() {
    delete additiveExpressionAst1;
    delete subAst2;
    delete multiplicativeExpressionAst3;
}
