// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void AdditiveExpression1::Dump(int depth) {
    TreeRender::push("AdditiveExpression");
    multiplicativeExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

AdditiveExpression1::~AdditiveExpression1() {
    delete multiplicativeExpressionAst1;
}

void AdditiveExpression2::Dump(int depth) {
    TreeRender::push("AdditiveExpression");
    additiveExpressionAst1->Dump(depth + 1);
    addAst2->Dump(depth + 1);
    multiplicativeExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

AdditiveExpression2::~AdditiveExpression2() {
    delete additiveExpressionAst1;
    delete addAst2;
    delete multiplicativeExpressionAst3;
}

void AdditiveExpression3::Dump(int depth) {
    TreeRender::push("AdditiveExpression");
    additiveExpressionAst1->Dump(depth + 1);
    subAst2->Dump(depth + 1);
    multiplicativeExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

AdditiveExpression3::~AdditiveExpression3() {
    delete additiveExpressionAst1;
    delete subAst2;
    delete multiplicativeExpressionAst3;
}
