// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void AndExpression1::Dump(int depth) {
    TreeRender::push("AndExpression");
    equalityExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

AndExpression1::~AndExpression1() {
    delete equalityExpressionAst1;
}

void AndExpression2::Dump(int depth) {
    TreeRender::push("AndExpression");
    andExpressionAst1->Dump(depth + 1);
    andAst2->Dump(depth + 1);
    equalityExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

AndExpression2::~AndExpression2() {
    delete andExpressionAst1;
    delete andAst2;
    delete equalityExpressionAst3;
}
