// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void AndExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AndExpression1" << std::endl;
    equalityExpressionAst1->Dump(depth + 1);
}

AndExpression1::~AndExpression1() {
    delete equalityExpressionAst1;
}

void AndExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AndExpression2" << std::endl;
    andExpressionAst1->Dump(depth + 1);
    andAst2->Dump(depth + 1);
    equalityExpressionAst3->Dump(depth + 1);
}

AndExpression2::~AndExpression2() {
    delete andExpressionAst1;
    delete andAst2;
    delete equalityExpressionAst3;
}
