// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void ArgumentExpressionList1::Dump(int depth) {
    TreeRender::push("ArgumentExpressionList");
    assignmentExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

ArgumentExpressionList1::~ArgumentExpressionList1() {
    delete assignmentExpressionAst1;
}

void ArgumentExpressionList2::Dump(int depth) {
    TreeRender::push("ArgumentExpressionList");
    argumentExpressionListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    assignmentExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

ArgumentExpressionList2::~ArgumentExpressionList2() {
    delete argumentExpressionListAst1;
    delete commaAst2;
    delete assignmentExpressionAst3;
}
