// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ArgumentExpressionList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ArgumentExpressionList1" << std::endl;
    assignmentExpressionAst1->Dump(depth + 1);
}

ArgumentExpressionList1::~ArgumentExpressionList1() {
    delete assignmentExpressionAst1;
}

void ArgumentExpressionList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ArgumentExpressionList2" << std::endl;
    argumentExpressionListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    assignmentExpressionAst3->Dump(depth + 1);
}

ArgumentExpressionList2::~ArgumentExpressionList2() {
    delete argumentExpressionListAst1;
    delete commaAst2;
    delete assignmentExpressionAst3;
}
