// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/expression/assignment_expression.h"

void AssignmentExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AssignmentExpression1" << std::endl;
    conditionalExpressionAst1->Dump(depth + 1);
}

AssignmentExpression1::~AssignmentExpression1() {
    delete conditionalExpressionAst1;
}

void AssignmentExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AssignmentExpression2" << std::endl;
    unaryExpressionAst1->Dump(depth + 1);
    assignmentOperatorAst2->Dump(depth + 1);
    assignmentExpressionAst3->Dump(depth + 1);
}

AssignmentExpression2::~AssignmentExpression2() {
    delete unaryExpressionAst1;
    delete assignmentOperatorAst2;
    delete assignmentExpressionAst3;
}
