// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void AssignmentExpression1::Dump(int depth) {
    TreeRender::push("AssignmentExpression");
    conditionalExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

AssignmentExpression1::~AssignmentExpression1() {
    delete conditionalExpressionAst1;
}

void AssignmentExpression2::Dump(int depth) {
    TreeRender::push("AssignmentExpression");
    unaryExpressionAst1->Dump(depth + 1);
    assignmentOperatorAst2->Dump(depth + 1);
    assignmentExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

AssignmentExpression2::~AssignmentExpression2() {
    delete unaryExpressionAst1;
    delete assignmentOperatorAst2;
    delete assignmentExpressionAst3;
}
