// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void CastExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "CastExpression1" << std::endl;
    unaryExpressionAst1->Dump(depth + 1);
}

CastExpression1::~CastExpression1() {
    delete unaryExpressionAst1;
}

void CastExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "CastExpression2" << std::endl;
    lRoundAst1->Dump(depth + 1);
    typeNameAst2->Dump(depth + 1);
    rRoundAst3->Dump(depth + 1);
    castExpressionAst4->Dump(depth + 1);
}

CastExpression2::~CastExpression2() {
    delete lRoundAst1;
    delete typeNameAst2;
    delete rRoundAst3;
    delete castExpressionAst4;
}
