// Generated by buildSrc/GenerateAST.py
#ifndef _CAST_EXPRESSION_H_
#define _CAST_EXPRESSION_H_

//#include "ast/ast.h"
class LRound;
class RRound;
class TypeName;
class UnaryExpression;

class CastExpression: public BasicAST {
public:
    virtual ~CastExpression() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class CastExpression1: public CastExpression {
public:
    UnaryExpression* unaryExpressionAst1;

    CastExpression1(
        UnaryExpression* unaryExpressionAst1
    ): unaryExpressionAst1(unaryExpressionAst1) {}

    virtual ~CastExpression1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class CastExpression2: public CastExpression {
public:
    LRound* lRoundAst1;
    TypeName* typeNameAst2;
    RRound* rRoundAst3;
    CastExpression* castExpressionAst4;

    CastExpression2(
        LRound* lRoundAst1,
        TypeName* typeNameAst2,
        RRound* rRoundAst3,
        CastExpression* castExpressionAst4
    ): lRoundAst1(lRoundAst1), typeNameAst2(typeNameAst2), rRoundAst3(rRoundAst3), castExpressionAst4(castExpressionAst4) {}

    virtual ~CastExpression2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _CAST_EXPRESSION_H_
