// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ConditionalExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ConditionalExpression1" << std::endl;
    logicalOrExpressionAst1->Dump(depth + 1);
}

ConditionalExpression1::~ConditionalExpression1() {
    delete logicalOrExpressionAst1;
}

void ConditionalExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ConditionalExpression2" << std::endl;
    logicalOrExpressionAst1->Dump(depth + 1);
    questionAst2->Dump(depth + 1);
    expressionAst3->Dump(depth + 1);
    colonAst4->Dump(depth + 1);
    conditionalExpressionAst5->Dump(depth + 1);
}

ConditionalExpression2::~ConditionalExpression2() {
    delete logicalOrExpressionAst1;
    delete questionAst2;
    delete expressionAst3;
    delete colonAst4;
    delete conditionalExpressionAst5;
}
