// Generated by buildSrc/GenerateAST.py
#ifndef _CONDITIONAL_EXPRESSION_H_
#define _CONDITIONAL_EXPRESSION_H_

#include "ast/ast.h"
//#header

class ConditionalExpression: public BasicAST {
public:
    virtual ~ConditionalExpression() {}
    virtual void GenerateIR(Context context) {}
    virtual void Dump(int depth) {}
};

class ConditionalExpression1: public ConditionalExpression {
public:
    LogicalOrExpression* logicalOrExpressionAst1;

    ConditionalExpression1(
        LogicalOrExpression* logicalOrExpressionAst1
    ): logicalOrExpressionAst1(logicalOrExpressionAst1) {}

    virtual ~ConditionalExpression1();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class ConditionalExpression2: public ConditionalExpression {
public:
    LogicalOrExpression* logicalOrExpressionAst1;
    Question* questionAst2;
    Expression* expressionAst3;
    Colon* colonAst4;
    ConditionalExpression* conditionalExpressionAst5;

    ConditionalExpression2(
        LogicalOrExpression* logicalOrExpressionAst1,
        Question* questionAst2,
        Expression* expressionAst3,
        Colon* colonAst4,
        ConditionalExpression* conditionalExpressionAst5
    ): logicalOrExpressionAst1(logicalOrExpressionAst1), questionAst2(questionAst2), expressionAst3(expressionAst3), colonAst4(colonAst4), conditionalExpressionAst5(conditionalExpressionAst5) {}

    virtual ~ConditionalExpression2();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_EXPRESSION_
#define _CLASS_EXPRESSION_
class Expression;
#endif //_CLASS_EXPRESSION_
#ifndef _CLASS_LOGICALOREXPRESSION_
#define _CLASS_LOGICALOREXPRESSION_
class LogicalOrExpression;
#endif //_CLASS_LOGICALOREXPRESSION_
#ifndef _CLASS_COLON_
#define _CLASS_COLON_
class Colon;
#endif //_CLASS_COLON_
#ifndef _CLASS_QUESTION_
#define _CLASS_QUESTION_
class Question;
#endif //_CLASS_QUESTION_

#endif // _CONDITIONAL_EXPRESSION_H_
