// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ConstantExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ConstantExpression1" << std::endl;
    conditionalExpressionAst1->Dump(depth + 1);
}

ConstantExpression1::~ConstantExpression1() {
    delete conditionalExpressionAst1;
}
