// Generated by buildSrc/GenerateAST.py
#ifndef _CONSTANT_EXPRESSION_H_
#define _CONSTANT_EXPRESSION_H_

//#include "ast/ast.h"
class ConditionalExpression;

class ConstantExpression: public BasicAST {
public:
    virtual ~ConstantExpression() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class ConstantExpression1: public ConstantExpression {
public:
    ConditionalExpression* conditionalExpressionAst1;

    ConstantExpression1(
        ConditionalExpression* conditionalExpressionAst1
    ): conditionalExpressionAst1(conditionalExpressionAst1) {}

    virtual ~ConstantExpression1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _CONSTANT_EXPRESSION_H_
