// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void ConstantExpression1::Dump(int depth) {
    TreeRender::push("ConstantExpression");
    conditionalExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

ConstantExpression1::~ConstantExpression1() {
    delete conditionalExpressionAst1;
}
