// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void EqualityExpression1::Dump(int depth) {
    TreeRender::push("EqualityExpression");
    relationalExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

EqualityExpression1::~EqualityExpression1() {
    delete relationalExpressionAst1;
}

void EqualityExpression2::Dump(int depth) {
    TreeRender::push("EqualityExpression");
    equalityExpressionAst1->Dump(depth + 1);
    eqOpAst2->Dump(depth + 1);
    relationalExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

EqualityExpression2::~EqualityExpression2() {
    delete equalityExpressionAst1;
    delete eqOpAst2;
    delete relationalExpressionAst3;
}

void EqualityExpression3::Dump(int depth) {
    TreeRender::push("EqualityExpression");
    equalityExpressionAst1->Dump(depth + 1);
    neOpAst2->Dump(depth + 1);
    relationalExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

EqualityExpression3::~EqualityExpression3() {
    delete equalityExpressionAst1;
    delete neOpAst2;
    delete relationalExpressionAst3;
}
