// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void EqualityExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "EqualityExpression1" << std::endl;
    relationalExpressionAst1->Dump(depth + 1);
}

EqualityExpression1::~EqualityExpression1() {
    delete relationalExpressionAst1;
}

void EqualityExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "EqualityExpression2" << std::endl;
    equalityExpressionAst1->Dump(depth + 1);
    eqOpAst2->Dump(depth + 1);
    relationalExpressionAst3->Dump(depth + 1);
}

EqualityExpression2::~EqualityExpression2() {
    delete equalityExpressionAst1;
    delete eqOpAst2;
    delete relationalExpressionAst3;
}

void EqualityExpression3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "EqualityExpression3" << std::endl;
    equalityExpressionAst1->Dump(depth + 1);
    neOpAst2->Dump(depth + 1);
    relationalExpressionAst3->Dump(depth + 1);
}

EqualityExpression3::~EqualityExpression3() {
    delete equalityExpressionAst1;
    delete neOpAst2;
    delete relationalExpressionAst3;
}
