// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ExclusiveOrExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ExclusiveOrExpression1" << std::endl;
    andExpressionAst1->Dump(depth + 1);
}

ExclusiveOrExpression1::~ExclusiveOrExpression1() {
    delete andExpressionAst1;
}

void ExclusiveOrExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ExclusiveOrExpression2" << std::endl;
    exclusiveOrExpressionAst1->Dump(depth + 1);
    caretAst2->Dump(depth + 1);
    andExpressionAst3->Dump(depth + 1);
}

ExclusiveOrExpression2::~ExclusiveOrExpression2() {
    delete exclusiveOrExpressionAst1;
    delete caretAst2;
    delete andExpressionAst3;
}
