// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void ExclusiveOrExpression1::Dump(int depth) {
    TreeRender::push("ExclusiveOrExpression");
    andExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

ExclusiveOrExpression1::~ExclusiveOrExpression1() {
    delete andExpressionAst1;
}

void ExclusiveOrExpression2::Dump(int depth) {
    TreeRender::push("ExclusiveOrExpression");
    exclusiveOrExpressionAst1->Dump(depth + 1);
    caretAst2->Dump(depth + 1);
    andExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

ExclusiveOrExpression2::~ExclusiveOrExpression2() {
    delete exclusiveOrExpressionAst1;
    delete caretAst2;
    delete andExpressionAst3;
}
