// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void Expression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Expression1" << std::endl;
    assignmentExpressionAst1->Dump(depth + 1);
}

Expression1::~Expression1() {
    delete assignmentExpressionAst1;
}

void Expression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Expression2" << std::endl;
    expressionAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    assignmentExpressionAst3->Dump(depth + 1);
}

Expression2::~Expression2() {
    delete expressionAst1;
    delete commaAst2;
    delete assignmentExpressionAst3;
}
