// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void Expression1::Dump(int depth) {
    TreeRender::push("Expression");
    assignmentExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

Expression1::~Expression1() {
    delete assignmentExpressionAst1;
}

void Expression2::Dump(int depth) {
    TreeRender::push("Expression");
    expressionAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    assignmentExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

Expression2::~Expression2() {
    delete expressionAst1;
    delete commaAst2;
    delete assignmentExpressionAst3;
}
