// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void InclusiveOrExpression1::Dump(int depth) {
    TreeRender::push("InclusiveOrExpression");
    exclusiveOrExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

InclusiveOrExpression1::~InclusiveOrExpression1() {
    delete exclusiveOrExpressionAst1;
}

void InclusiveOrExpression2::Dump(int depth) {
    TreeRender::push("InclusiveOrExpression");
    inclusiveOrExpressionAst1->Dump(depth + 1);
    verticalAst2->Dump(depth + 1);
    exclusiveOrExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

InclusiveOrExpression2::~InclusiveOrExpression2() {
    delete inclusiveOrExpressionAst1;
    delete verticalAst2;
    delete exclusiveOrExpressionAst3;
}
