// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/expression/inclusive_or_expression.h"

void InclusiveOrExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "InclusiveOrExpression1" << std::endl;
    exclusiveOrExpressionAst1->Dump(depth + 1);
}

InclusiveOrExpression1::~InclusiveOrExpression1() {
    delete exclusiveOrExpressionAst1;
}

void InclusiveOrExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "InclusiveOrExpression2" << std::endl;
    inclusiveOrExpressionAst1->Dump(depth + 1);
    verticalAst2->Dump(depth + 1);
    exclusiveOrExpressionAst3->Dump(depth + 1);
}

InclusiveOrExpression2::~InclusiveOrExpression2() {
    delete inclusiveOrExpressionAst1;
    delete verticalAst2;
    delete exclusiveOrExpressionAst3;
}
