// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void LogicalOrExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "LogicalOrExpression1" << std::endl;
    logicalAndExpressionAst1->Dump(depth + 1);
}

LogicalOrExpression1::~LogicalOrExpression1() {
    delete logicalAndExpressionAst1;
}

void LogicalOrExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "LogicalOrExpression2" << std::endl;
    logicalOrExpressionAst1->Dump(depth + 1);
    orOpAst2->Dump(depth + 1);
    logicalAndExpressionAst3->Dump(depth + 1);
}

LogicalOrExpression2::~LogicalOrExpression2() {
    delete logicalOrExpressionAst1;
    delete orOpAst2;
    delete logicalAndExpressionAst3;
}
