// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void LogicalAndExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "LogicalAndExpression1" << std::endl;
    inclusiveOrExpressionAst1->Dump(depth + 1);
}

LogicalAndExpression1::~LogicalAndExpression1() {
    delete inclusiveOrExpressionAst1;
}

void LogicalAndExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "LogicalAndExpression2" << std::endl;
    logicalAndExpressionAst1->Dump(depth + 1);
    andOpAst2->Dump(depth + 1);
    inclusiveOrExpressionAst3->Dump(depth + 1);
}

LogicalAndExpression2::~LogicalAndExpression2() {
    delete logicalAndExpressionAst1;
    delete andOpAst2;
    delete inclusiveOrExpressionAst3;
}
