// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void LogicalAndExpression1::Dump(int depth) {
    TreeRender::push("LogicalAndExpression");
    inclusiveOrExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

LogicalAndExpression1::~LogicalAndExpression1() {
    delete inclusiveOrExpressionAst1;
}

void LogicalAndExpression2::Dump(int depth) {
    TreeRender::push("LogicalAndExpression");
    logicalAndExpressionAst1->Dump(depth + 1);
    andOpAst2->Dump(depth + 1);
    inclusiveOrExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

LogicalAndExpression2::~LogicalAndExpression2() {
    delete logicalAndExpressionAst1;
    delete andOpAst2;
    delete inclusiveOrExpressionAst3;
}
