// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void LogicalOrExpression1::Dump(int depth) {
    TreeRender::push("LogicalOrExpression");
    logicalAndExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

LogicalOrExpression1::~LogicalOrExpression1() {
    delete logicalAndExpressionAst1;
}

void LogicalOrExpression2::Dump(int depth) {
    TreeRender::push("LogicalOrExpression");
    logicalOrExpressionAst1->Dump(depth + 1);
    orOpAst2->Dump(depth + 1);
    logicalAndExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

LogicalOrExpression2::~LogicalOrExpression2() {
    delete logicalOrExpressionAst1;
    delete orOpAst2;
    delete logicalAndExpressionAst3;
}
