// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void MultiplicativeExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "MultiplicativeExpression1" << std::endl;
    castExpressionAst1->Dump(depth + 1);
}

MultiplicativeExpression1::~MultiplicativeExpression1() {
    delete castExpressionAst1;
}

void MultiplicativeExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "MultiplicativeExpression2" << std::endl;
    multiplicativeExpressionAst1->Dump(depth + 1);
    mulAst2->Dump(depth + 1);
    castExpressionAst3->Dump(depth + 1);
}

MultiplicativeExpression2::~MultiplicativeExpression2() {
    delete multiplicativeExpressionAst1;
    delete mulAst2;
    delete castExpressionAst3;
}

void MultiplicativeExpression3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "MultiplicativeExpression3" << std::endl;
    multiplicativeExpressionAst1->Dump(depth + 1);
    divAst2->Dump(depth + 1);
    castExpressionAst3->Dump(depth + 1);
}

MultiplicativeExpression3::~MultiplicativeExpression3() {
    delete multiplicativeExpressionAst1;
    delete divAst2;
    delete castExpressionAst3;
}

void MultiplicativeExpression4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "MultiplicativeExpression4" << std::endl;
    multiplicativeExpressionAst1->Dump(depth + 1);
    modAst2->Dump(depth + 1);
    castExpressionAst3->Dump(depth + 1);
}

MultiplicativeExpression4::~MultiplicativeExpression4() {
    delete multiplicativeExpressionAst1;
    delete modAst2;
    delete castExpressionAst3;
}
