// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void PrimaryExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "PrimaryExpression1" << std::endl;
    identifierAst1->Dump(depth + 1);
}

PrimaryExpression1::~PrimaryExpression1() {
    delete identifierAst1;
}

void PrimaryExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "PrimaryExpression2" << std::endl;
    constantAst1->Dump(depth + 1);
}

PrimaryExpression2::~PrimaryExpression2() {
    delete constantAst1;
}

void PrimaryExpression3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "PrimaryExpression3" << std::endl;
    stringLiteralAst1->Dump(depth + 1);
}

PrimaryExpression3::~PrimaryExpression3() {
    delete stringLiteralAst1;
}

void PrimaryExpression4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "PrimaryExpression4" << std::endl;
    lRoundAst1->Dump(depth + 1);
    expressionAst2->Dump(depth + 1);
    rRoundAst3->Dump(depth + 1);
}

PrimaryExpression4::~PrimaryExpression4() {
    delete lRoundAst1;
    delete expressionAst2;
    delete rRoundAst3;
}
