// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void RelationalExpression1::Dump(int depth) {
    TreeRender::push("RelationalExpression");
    shiftExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

RelationalExpression1::~RelationalExpression1() {
    delete shiftExpressionAst1;
}

void RelationalExpression2::Dump(int depth) {
    TreeRender::push("RelationalExpression");
    relationalExpressionAst1->Dump(depth + 1);
    lAngleAst2->Dump(depth + 1);
    shiftExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

RelationalExpression2::~RelationalExpression2() {
    delete relationalExpressionAst1;
    delete lAngleAst2;
    delete shiftExpressionAst3;
}

void RelationalExpression3::Dump(int depth) {
    TreeRender::push("RelationalExpression");
    relationalExpressionAst1->Dump(depth + 1);
    rAngleAst2->Dump(depth + 1);
    shiftExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

RelationalExpression3::~RelationalExpression3() {
    delete relationalExpressionAst1;
    delete rAngleAst2;
    delete shiftExpressionAst3;
}

void RelationalExpression4::Dump(int depth) {
    TreeRender::push("RelationalExpression");
    relationalExpressionAst1->Dump(depth + 1);
    leOpAst2->Dump(depth + 1);
    shiftExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

RelationalExpression4::~RelationalExpression4() {
    delete relationalExpressionAst1;
    delete leOpAst2;
    delete shiftExpressionAst3;
}

void RelationalExpression5::Dump(int depth) {
    TreeRender::push("RelationalExpression");
    relationalExpressionAst1->Dump(depth + 1);
    geOpAst2->Dump(depth + 1);
    shiftExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

RelationalExpression5::~RelationalExpression5() {
    delete relationalExpressionAst1;
    delete geOpAst2;
    delete shiftExpressionAst3;
}
