// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ShiftExpression1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ShiftExpression1" << std::endl;
    additiveExpressionAst1->Dump(depth + 1);
}

ShiftExpression1::~ShiftExpression1() {
    delete additiveExpressionAst1;
}

void ShiftExpression2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ShiftExpression2" << std::endl;
    shiftExpressionAst1->Dump(depth + 1);
    leftOpAst2->Dump(depth + 1);
    additiveExpressionAst3->Dump(depth + 1);
}

ShiftExpression2::~ShiftExpression2() {
    delete shiftExpressionAst1;
    delete leftOpAst2;
    delete additiveExpressionAst3;
}

void ShiftExpression3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ShiftExpression3" << std::endl;
    shiftExpressionAst1->Dump(depth + 1);
    rightOpAst2->Dump(depth + 1);
    additiveExpressionAst3->Dump(depth + 1);
}

ShiftExpression3::~ShiftExpression3() {
    delete shiftExpressionAst1;
    delete rightOpAst2;
    delete additiveExpressionAst3;
}
