// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void UnaryOperator1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "UnaryOperator1" << std::endl;
    andAst1->Dump(depth + 1);
}

UnaryOperator1::~UnaryOperator1() {
    delete andAst1;
}

void UnaryOperator2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "UnaryOperator2" << std::endl;
    mulAst1->Dump(depth + 1);
}

UnaryOperator2::~UnaryOperator2() {
    delete mulAst1;
}

void UnaryOperator3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "UnaryOperator3" << std::endl;
    addAst1->Dump(depth + 1);
}

UnaryOperator3::~UnaryOperator3() {
    delete addAst1;
}

void UnaryOperator4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "UnaryOperator4" << std::endl;
    subAst1->Dump(depth + 1);
}

UnaryOperator4::~UnaryOperator4() {
    delete subAst1;
}

void UnaryOperator5::Dump(int depth) {
    std::cout << "[" << depth << "] " << "UnaryOperator5" << std::endl;
    tildeAst1->Dump(depth + 1);
}

UnaryOperator5::~UnaryOperator5() {
    delete tildeAst1;
}

void UnaryOperator6::Dump(int depth) {
    std::cout << "[" << depth << "] " << "UnaryOperator6" << std::endl;
    exclamationAst1->Dump(depth + 1);
}

UnaryOperator6::~UnaryOperator6() {
    delete exclamationAst1;
}
