// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void UnaryOperator1::Dump(int depth) {
    TreeRender::push("UnaryOperator");
    andAst1->Dump(depth + 1);
    TreeRender::pop();
}

UnaryOperator1::~UnaryOperator1() {
    delete andAst1;
}

void UnaryOperator2::Dump(int depth) {
    TreeRender::push("UnaryOperator");
    mulAst1->Dump(depth + 1);
    TreeRender::pop();
}

UnaryOperator2::~UnaryOperator2() {
    delete mulAst1;
}

void UnaryOperator3::Dump(int depth) {
    TreeRender::push("UnaryOperator");
    addAst1->Dump(depth + 1);
    TreeRender::pop();
}

UnaryOperator3::~UnaryOperator3() {
    delete addAst1;
}

void UnaryOperator4::Dump(int depth) {
    TreeRender::push("UnaryOperator");
    subAst1->Dump(depth + 1);
    TreeRender::pop();
}

UnaryOperator4::~UnaryOperator4() {
    delete subAst1;
}

void UnaryOperator5::Dump(int depth) {
    TreeRender::push("UnaryOperator");
    tildeAst1->Dump(depth + 1);
    TreeRender::pop();
}

UnaryOperator5::~UnaryOperator5() {
    delete tildeAst1;
}

void UnaryOperator6::Dump(int depth) {
    TreeRender::push("UnaryOperator");
    exclamationAst1->Dump(depth + 1);
    TreeRender::pop();
}

UnaryOperator6::~UnaryOperator6() {
    delete exclamationAst1;
}
