// Generated by buildSrc/GenerateAST.py
#ifndef _UNARY_EXPRESSION_H_
#define _UNARY_EXPRESSION_H_

#include "ast/ast.h"
//#header

class UnaryExpression: public BasicAST {
public:
    virtual ~UnaryExpression() {}
    virtual void GenerateIR(Context context) {}
    virtual void Dump(int depth) {}
};

class UnaryExpression1: public UnaryExpression {
public:
    PostfixExpression* postfixExpressionAst1;

    UnaryExpression1(
        PostfixExpression* postfixExpressionAst1
    ): postfixExpressionAst1(postfixExpressionAst1) {}

    virtual ~UnaryExpression1();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class UnaryExpression2: public UnaryExpression {
public:
    IncOp* incOpAst1;
    UnaryExpression* unaryExpressionAst2;

    UnaryExpression2(
        IncOp* incOpAst1,
        UnaryExpression* unaryExpressionAst2
    ): incOpAst1(incOpAst1), unaryExpressionAst2(unaryExpressionAst2) {}

    virtual ~UnaryExpression2();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class UnaryExpression3: public UnaryExpression {
public:
    DecOp* decOpAst1;
    UnaryExpression* unaryExpressionAst2;

    UnaryExpression3(
        DecOp* decOpAst1,
        UnaryExpression* unaryExpressionAst2
    ): decOpAst1(decOpAst1), unaryExpressionAst2(unaryExpressionAst2) {}

    virtual ~UnaryExpression3();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class UnaryExpression4: public UnaryExpression {
public:
    UnaryOperator* unaryOperatorAst1;
    CastExpression* castExpressionAst2;

    UnaryExpression4(
        UnaryOperator* unaryOperatorAst1,
        CastExpression* castExpressionAst2
    ): unaryOperatorAst1(unaryOperatorAst1), castExpressionAst2(castExpressionAst2) {}

    virtual ~UnaryExpression4();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class UnaryExpression5: public UnaryExpression {
public:
    Sizeof* sizeofAst1;
    UnaryExpression* unaryExpressionAst2;

    UnaryExpression5(
        Sizeof* sizeofAst1,
        UnaryExpression* unaryExpressionAst2
    ): sizeofAst1(sizeofAst1), unaryExpressionAst2(unaryExpressionAst2) {}

    virtual ~UnaryExpression5();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class UnaryExpression6: public UnaryExpression {
public:
    Sizeof* sizeofAst1;
    LRound* lRoundAst2;
    TypeName* typeNameAst3;
    RRound* rRoundAst4;

    UnaryExpression6(
        Sizeof* sizeofAst1,
        LRound* lRoundAst2,
        TypeName* typeNameAst3,
        RRound* rRoundAst4
    ): sizeofAst1(sizeofAst1), lRoundAst2(lRoundAst2), typeNameAst3(typeNameAst3), rRoundAst4(rRoundAst4) {}

    virtual ~UnaryExpression6();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_LROUND_
#define _CLASS_LROUND_
class LRound;
#endif //_CLASS_LROUND_
#ifndef _CLASS_CASTEXPRESSION_
#define _CLASS_CASTEXPRESSION_
class CastExpression;
#endif //_CLASS_CASTEXPRESSION_
#ifndef _CLASS_RROUND_
#define _CLASS_RROUND_
class RRound;
#endif //_CLASS_RROUND_
#ifndef _CLASS_SIZEOF_
#define _CLASS_SIZEOF_
class Sizeof;
#endif //_CLASS_SIZEOF_
#ifndef _CLASS_INCOP_
#define _CLASS_INCOP_
class IncOp;
#endif //_CLASS_INCOP_
#ifndef _CLASS_TYPENAME_
#define _CLASS_TYPENAME_
class TypeName;
#endif //_CLASS_TYPENAME_
#ifndef _CLASS_DECOP_
#define _CLASS_DECOP_
class DecOp;
#endif //_CLASS_DECOP_
#ifndef _CLASS_POSTFIXEXPRESSION_
#define _CLASS_POSTFIXEXPRESSION_
class PostfixExpression;
#endif //_CLASS_POSTFIXEXPRESSION_
#ifndef _CLASS_UNARYOPERATOR_
#define _CLASS_UNARYOPERATOR_
class UnaryOperator;
#endif //_CLASS_UNARYOPERATOR_

#endif // _UNARY_EXPRESSION_H_
