// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void UnaryExpression1::Dump(int depth) {
    TreeRender::push("UnaryExpression");
    postfixExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

UnaryExpression1::~UnaryExpression1() {
    delete postfixExpressionAst1;
}

void UnaryExpression2::Dump(int depth) {
    TreeRender::push("UnaryExpression");
    incOpAst1->Dump(depth + 1);
    unaryExpressionAst2->Dump(depth + 1);
    TreeRender::pop();
}

UnaryExpression2::~UnaryExpression2() {
    delete incOpAst1;
    delete unaryExpressionAst2;
}

void UnaryExpression3::Dump(int depth) {
    TreeRender::push("UnaryExpression");
    decOpAst1->Dump(depth + 1);
    unaryExpressionAst2->Dump(depth + 1);
    TreeRender::pop();
}

UnaryExpression3::~UnaryExpression3() {
    delete decOpAst1;
    delete unaryExpressionAst2;
}

void UnaryExpression4::Dump(int depth) {
    TreeRender::push("UnaryExpression");
    unaryOperatorAst1->Dump(depth + 1);
    castExpressionAst2->Dump(depth + 1);
    TreeRender::pop();
}

UnaryExpression4::~UnaryExpression4() {
    delete unaryOperatorAst1;
    delete castExpressionAst2;
}

void UnaryExpression5::Dump(int depth) {
    TreeRender::push("UnaryExpression");
    sizeofAst1->Dump(depth + 1);
    unaryExpressionAst2->Dump(depth + 1);
    TreeRender::pop();
}

UnaryExpression5::~UnaryExpression5() {
    delete sizeofAst1;
    delete unaryExpressionAst2;
}

void UnaryExpression6::Dump(int depth) {
    TreeRender::push("UnaryExpression");
    sizeofAst1->Dump(depth + 1);
    lRoundAst2->Dump(depth + 1);
    typeNameAst3->Dump(depth + 1);
    rRoundAst4->Dump(depth + 1);
    TreeRender::pop();
}

UnaryExpression6::~UnaryExpression6() {
    delete sizeofAst1;
    delete lRoundAst2;
    delete typeNameAst3;
    delete rRoundAst4;
}
