// Generated by buildSrc/GenerateAST.py
#ifndef _ABSTRACT_DECLARATOR_H_
#define _ABSTRACT_DECLARATOR_H_

//#include "ast/ast.h"
class DirectAbstractDeclarator;
class Pointer;

class AbstractDeclarator: public BasicAST {
public:
    virtual ~AbstractDeclarator() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class AbstractDeclarator1: public AbstractDeclarator {
public:
    Pointer* pointerAst1;

    AbstractDeclarator1(
        Pointer* pointerAst1
    ): pointerAst1(pointerAst1) {}

    virtual ~AbstractDeclarator1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class AbstractDeclarator2: public AbstractDeclarator {
public:
    DirectAbstractDeclarator* directAbstractDeclaratorAst1;

    AbstractDeclarator2(
        DirectAbstractDeclarator* directAbstractDeclaratorAst1
    ): directAbstractDeclaratorAst1(directAbstractDeclaratorAst1) {}

    virtual ~AbstractDeclarator2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class AbstractDeclarator3: public AbstractDeclarator {
public:
    Pointer* pointerAst1;
    DirectAbstractDeclarator* directAbstractDeclaratorAst2;

    AbstractDeclarator3(
        Pointer* pointerAst1,
        DirectAbstractDeclarator* directAbstractDeclaratorAst2
    ): pointerAst1(pointerAst1), directAbstractDeclaratorAst2(directAbstractDeclaratorAst2) {}

    virtual ~AbstractDeclarator3();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _ABSTRACT_DECLARATOR_H_
