// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void AbstractDeclarator1::Dump(int depth) {
    TreeRender::push("AbstractDeclarator");
    pointerAst1->Dump(depth + 1);
    TreeRender::pop();
}

AbstractDeclarator1::~AbstractDeclarator1() {
    delete pointerAst1;
}

void AbstractDeclarator2::Dump(int depth) {
    TreeRender::push("AbstractDeclarator");
    directAbstractDeclaratorAst1->Dump(depth + 1);
    TreeRender::pop();
}

AbstractDeclarator2::~AbstractDeclarator2() {
    delete directAbstractDeclaratorAst1;
}

void AbstractDeclarator3::Dump(int depth) {
    TreeRender::push("AbstractDeclarator");
    pointerAst1->Dump(depth + 1);
    directAbstractDeclaratorAst2->Dump(depth + 1);
    TreeRender::pop();
}

AbstractDeclarator3::~AbstractDeclarator3() {
    delete pointerAst1;
    delete directAbstractDeclaratorAst2;
}
