// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/decl/abstract_declarator.h"

void AbstractDeclarator1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AbstractDeclarator1" << std::endl;
    pointerAst1->Dump(depth + 1);
}

AbstractDeclarator1::~AbstractDeclarator1() {
    delete pointerAst1;
}

void AbstractDeclarator2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AbstractDeclarator2" << std::endl;
    directAbstractDeclaratorAst1->Dump(depth + 1);
}

AbstractDeclarator2::~AbstractDeclarator2() {
    delete directAbstractDeclaratorAst1;
}

void AbstractDeclarator3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "AbstractDeclarator3" << std::endl;
    pointerAst1->Dump(depth + 1);
    directAbstractDeclaratorAst2->Dump(depth + 1);
}

AbstractDeclarator3::~AbstractDeclarator3() {
    delete pointerAst1;
    delete directAbstractDeclaratorAst2;
}
