// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void Declarator1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Declarator1" << std::endl;
    pointerAst1->Dump(depth + 1);
    directDeclaratorAst2->Dump(depth + 1);
}

Declarator1::~Declarator1() {
    delete pointerAst1;
    delete directDeclaratorAst2;
}

void Declarator2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Declarator2" << std::endl;
    directDeclaratorAst1->Dump(depth + 1);
}

Declarator2::~Declarator2() {
    delete directDeclaratorAst1;
}
