// Generated by buildSrc/GenerateAST.py
#ifndef _DECLARATION_H_
#define _DECLARATION_H_

#include "ast/ast.h"
//#header

class Declaration: public BasicAST {
public:
    virtual ~Declaration() {}
    virtual void GenerateIR(Context context) {}
    virtual void Dump(int depth) {}
};

class Declaration1: public Declaration {
public:
    DeclarationSpecifiers* declarationSpecifiersAst1;
    SimicolonSingle* simicolonSingleAst2;

    Declaration1(
        DeclarationSpecifiers* declarationSpecifiersAst1,
        SimicolonSingle* simicolonSingleAst2
    ): declarationSpecifiersAst1(declarationSpecifiersAst1), simicolonSingleAst2(simicolonSingleAst2) {}

    virtual ~Declaration1();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class Declaration2: public Declaration {
public:
    DeclarationSpecifiers* declarationSpecifiersAst1;
    InitDeclaratorList* initDeclaratorListAst2;
    SimicolonSingle* simicolonSingleAst3;

    Declaration2(
        DeclarationSpecifiers* declarationSpecifiersAst1,
        InitDeclaratorList* initDeclaratorListAst2,
        SimicolonSingle* simicolonSingleAst3
    ): declarationSpecifiersAst1(declarationSpecifiersAst1), initDeclaratorListAst2(initDeclaratorListAst2), simicolonSingleAst3(simicolonSingleAst3) {}

    virtual ~Declaration2();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_DECLARATIONSPECIFIERS_
#define _CLASS_DECLARATIONSPECIFIERS_
class DeclarationSpecifiers;
#endif //_CLASS_DECLARATIONSPECIFIERS_
#ifndef _CLASS_INITDECLARATORLIST_
#define _CLASS_INITDECLARATORLIST_
class InitDeclaratorList;
#endif //_CLASS_INITDECLARATORLIST_
#ifndef _CLASS_SIMICOLONSINGLE_
#define _CLASS_SIMICOLONSINGLE_
class SimicolonSingle;
#endif //_CLASS_SIMICOLONSINGLE_

#endif // _DECLARATION_H_
