// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void DeclarationSpecifiers1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "DeclarationSpecifiers1" << std::endl;
    storageClassSpecifierAst1->Dump(depth + 1);
}

DeclarationSpecifiers1::~DeclarationSpecifiers1() {
    delete storageClassSpecifierAst1;
}

void DeclarationSpecifiers2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "DeclarationSpecifiers2" << std::endl;
    storageClassSpecifierAst1->Dump(depth + 1);
    declarationSpecifiersAst2->Dump(depth + 1);
}

DeclarationSpecifiers2::~DeclarationSpecifiers2() {
    delete storageClassSpecifierAst1;
    delete declarationSpecifiersAst2;
}

void DeclarationSpecifiers3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "DeclarationSpecifiers3" << std::endl;
    typeSpecifierAst1->Dump(depth + 1);
}

DeclarationSpecifiers3::~DeclarationSpecifiers3() {
    delete typeSpecifierAst1;
}

void DeclarationSpecifiers4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "DeclarationSpecifiers4" << std::endl;
    typeSpecifierAst1->Dump(depth + 1);
    declarationSpecifiersAst2->Dump(depth + 1);
}

DeclarationSpecifiers4::~DeclarationSpecifiers4() {
    delete typeSpecifierAst1;
    delete declarationSpecifiersAst2;
}

void DeclarationSpecifiers5::Dump(int depth) {
    std::cout << "[" << depth << "] " << "DeclarationSpecifiers5" << std::endl;
    typeQualifierAst1->Dump(depth + 1);
}

DeclarationSpecifiers5::~DeclarationSpecifiers5() {
    delete typeQualifierAst1;
}

void DeclarationSpecifiers6::Dump(int depth) {
    std::cout << "[" << depth << "] " << "DeclarationSpecifiers6" << std::endl;
    typeQualifierAst1->Dump(depth + 1);
    declarationSpecifiersAst2->Dump(depth + 1);
}

DeclarationSpecifiers6::~DeclarationSpecifiers6() {
    delete typeQualifierAst1;
    delete declarationSpecifiersAst2;
}
