// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void Declarator1::Dump(int depth) {
    TreeRender::push("Declarator");
    pointerAst1->Dump(depth + 1);
    directDeclaratorAst2->Dump(depth + 1);
    TreeRender::pop();
}

Declarator1::~Declarator1() {
    delete pointerAst1;
    delete directDeclaratorAst2;
}

void Declarator2::Dump(int depth) {
    TreeRender::push("Declarator");
    directDeclaratorAst1->Dump(depth + 1);
    TreeRender::pop();
}

Declarator2::~Declarator2() {
    delete directDeclaratorAst1;
}
