// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/decl/enumerator.h"

void Enumerator1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Enumerator1" << std::endl;
    identifierAst1->Dump(depth + 1);
}

Enumerator1::~Enumerator1() {
    delete identifierAst1;
}

void Enumerator2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Enumerator2" << std::endl;
    identifierAst1->Dump(depth + 1);
    eqAst2->Dump(depth + 1);
    constantExpressionAst3->Dump(depth + 1);
}

Enumerator2::~Enumerator2() {
    delete identifierAst1;
    delete eqAst2;
    delete constantExpressionAst3;
}
