// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/decl/enumerator_list.h"

void EnumeratorList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "EnumeratorList1" << std::endl;
    enumeratorAst1->Dump(depth + 1);
}

EnumeratorList1::~EnumeratorList1() {
    delete enumeratorAst1;
}

void EnumeratorList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "EnumeratorList2" << std::endl;
    enumeratorListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    enumeratorAst3->Dump(depth + 1);
}

EnumeratorList2::~EnumeratorList2() {
    delete enumeratorListAst1;
    delete commaAst2;
    delete enumeratorAst3;
}
