// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void EnumeratorList1::Dump(int depth) {
    TreeRender::push("EnumeratorList");
    enumeratorAst1->Dump(depth + 1);
    TreeRender::pop();
}

EnumeratorList1::~EnumeratorList1() {
    delete enumeratorAst1;
}

void EnumeratorList2::Dump(int depth) {
    TreeRender::push("EnumeratorList");
    enumeratorListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    enumeratorAst3->Dump(depth + 1);
    TreeRender::pop();
}

EnumeratorList2::~EnumeratorList2() {
    delete enumeratorListAst1;
    delete commaAst2;
    delete enumeratorAst3;
}
