// Generated by buildSrc/GenerateAST.py
#ifndef _ENUMERATOR_H_
#define _ENUMERATOR_H_

#include "ast/ast.h"
//#header

class Enumerator: public BasicAST {
public:
    virtual ~Enumerator() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class Enumerator1: public Enumerator {
public:
    Identifier* identifierAst1;

    Enumerator1(
        Identifier* identifierAst1
    ): identifierAst1(identifierAst1) {}

    virtual ~Enumerator1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class Enumerator2: public Enumerator {
public:
    Identifier* identifierAst1;
    Eq* eqAst2;
    ConstantExpression* constantExpressionAst3;

    Enumerator2(
        Identifier* identifierAst1,
        Eq* eqAst2,
        ConstantExpression* constantExpressionAst3
    ): identifierAst1(identifierAst1), eqAst2(eqAst2), constantExpressionAst3(constantExpressionAst3) {}

    virtual ~Enumerator2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_CONSTANTEXPRESSION_
#define _CLASS_CONSTANTEXPRESSION_
class ConstantExpression;
#endif //_CLASS_CONSTANTEXPRESSION_
#ifndef _CLASS_EQ_
#define _CLASS_EQ_
class Eq;
#endif //_CLASS_EQ_
#ifndef _CLASS_IDENTIFIER_
#define _CLASS_IDENTIFIER_
class Identifier;
#endif //_CLASS_IDENTIFIER_

#endif // _ENUMERATOR_H_
