// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void Enumerator1::Dump(int depth) {
    TreeRender::push("Enumerator");
    identifierAst1->Dump(depth + 1);
    TreeRender::pop();
}

Enumerator1::~Enumerator1() {
    delete identifierAst1;
}

void Enumerator2::Dump(int depth) {
    TreeRender::push("Enumerator");
    identifierAst1->Dump(depth + 1);
    eqAst2->Dump(depth + 1);
    constantExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

Enumerator2::~Enumerator2() {
    delete identifierAst1;
    delete eqAst2;
    delete constantExpressionAst3;
}
