// Generated by buildSrc/GenerateAST.py
#ifndef _ENUMERATOR_LIST_H_
#define _ENUMERATOR_LIST_H_

//#include "ast/ast.h"
class Comma;
class Enumerator;

class EnumeratorList: public BasicAST {
public:
    virtual ~EnumeratorList() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class EnumeratorList1: public EnumeratorList {
public:
    Enumerator* enumeratorAst1;

    EnumeratorList1(
        Enumerator* enumeratorAst1
    ): enumeratorAst1(enumeratorAst1) {}

    virtual ~EnumeratorList1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class EnumeratorList2: public EnumeratorList {
public:
    EnumeratorList* enumeratorListAst1;
    Comma* commaAst2;
    Enumerator* enumeratorAst3;

    EnumeratorList2(
        EnumeratorList* enumeratorListAst1,
        Comma* commaAst2,
        Enumerator* enumeratorAst3
    ): enumeratorListAst1(enumeratorListAst1), commaAst2(commaAst2), enumeratorAst3(enumeratorAst3) {}

    virtual ~EnumeratorList2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _ENUMERATOR_LIST_H_
