// Generated by buildSrc/GenerateAST.py
#ifndef _IDENTIFIER_LIST_H_
#define _IDENTIFIER_LIST_H_

#include "ast/ast.h"
//#header

class IdentifierList: public BasicAST {
public:
    virtual ~IdentifierList() {}
    virtual void GenerateIR(Context context) {}
    virtual void Dump(int depth) {}
};

class IdentifierList1: public IdentifierList {
public:
    Identifier* identifierAst1;

    IdentifierList1(
        Identifier* identifierAst1
    ): identifierAst1(identifierAst1) {}

    virtual ~IdentifierList1();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class IdentifierList2: public IdentifierList {
public:
    IdentifierList* identifierListAst1;
    Comma* commaAst2;
    Identifier* identifierAst3;

    IdentifierList2(
        IdentifierList* identifierListAst1,
        Comma* commaAst2,
        Identifier* identifierAst3
    ): identifierListAst1(identifierListAst1), commaAst2(commaAst2), identifierAst3(identifierAst3) {}

    virtual ~IdentifierList2();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_COMMA_
#define _CLASS_COMMA_
class Comma;
#endif //_CLASS_COMMA_
#ifndef _CLASS_IDENTIFIER_
#define _CLASS_IDENTIFIER_
class Identifier;
#endif //_CLASS_IDENTIFIER_

#endif // _IDENTIFIER_LIST_H_
