// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void IdentifierList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "IdentifierList1" << std::endl;
    identifierAst1->Dump(depth + 1);
}

IdentifierList1::~IdentifierList1() {
    delete identifierAst1;
}

void IdentifierList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "IdentifierList2" << std::endl;
    identifierListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    identifierAst3->Dump(depth + 1);
}

IdentifierList2::~IdentifierList2() {
    delete identifierListAst1;
    delete commaAst2;
    delete identifierAst3;
}
