// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void IdentifierList1::Dump(int depth) {
    TreeRender::push("IdentifierList");
    identifierAst1->Dump(depth + 1);
    TreeRender::pop();
}

IdentifierList1::~IdentifierList1() {
    delete identifierAst1;
}

void IdentifierList2::Dump(int depth) {
    TreeRender::push("IdentifierList");
    identifierListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    identifierAst3->Dump(depth + 1);
    TreeRender::pop();
}

IdentifierList2::~IdentifierList2() {
    delete identifierListAst1;
    delete commaAst2;
    delete identifierAst3;
}
