// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void Initializer1::Dump(int depth) {
    TreeRender::push("Initializer");
    assignmentExpressionAst1->Dump(depth + 1);
    TreeRender::pop();
}

Initializer1::~Initializer1() {
    delete assignmentExpressionAst1;
}

void Initializer2::Dump(int depth) {
    TreeRender::push("Initializer");
    lCurlyAst1->Dump(depth + 1);
    initializerListAst2->Dump(depth + 1);
    rCurlyAst3->Dump(depth + 1);
    TreeRender::pop();
}

Initializer2::~Initializer2() {
    delete lCurlyAst1;
    delete initializerListAst2;
    delete rCurlyAst3;
}

void Initializer3::Dump(int depth) {
    TreeRender::push("Initializer");
    lCurlyAst1->Dump(depth + 1);
    initializerListAst2->Dump(depth + 1);
    commaAst3->Dump(depth + 1);
    rCurlyAst4->Dump(depth + 1);
    TreeRender::pop();
}

Initializer3::~Initializer3() {
    delete lCurlyAst1;
    delete initializerListAst2;
    delete commaAst3;
    delete rCurlyAst4;
}
