// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void InitDeclaratorList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "InitDeclaratorList1" << std::endl;
    initDeclaratorAst1->Dump(depth + 1);
}

InitDeclaratorList1::~InitDeclaratorList1() {
    delete initDeclaratorAst1;
}

void InitDeclaratorList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "InitDeclaratorList2" << std::endl;
    initDeclaratorListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    initDeclaratorAst3->Dump(depth + 1);
}

InitDeclaratorList2::~InitDeclaratorList2() {
    delete initDeclaratorListAst1;
    delete commaAst2;
    delete initDeclaratorAst3;
}
