// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void InitializerList1::Dump(int depth) {
    TreeRender::push("InitializerList");
    initializerAst1->Dump(depth + 1);
    TreeRender::pop();
}

InitializerList1::~InitializerList1() {
    delete initializerAst1;
}

void InitializerList2::Dump(int depth) {
    TreeRender::push("InitializerList");
    initializerListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    initializerAst3->Dump(depth + 1);
    TreeRender::pop();
}

InitializerList2::~InitializerList2() {
    delete initializerListAst1;
    delete commaAst2;
    delete initializerAst3;
}
