// Generated by buildSrc/GenerateAST.py
#ifndef _INIT_DECLARATOR_LIST_H_
#define _INIT_DECLARATOR_LIST_H_

//#include "ast/ast.h"
class Comma;
class InitDeclarator;

class InitDeclaratorList: public BasicAST {
public:
    std::shared_ptr<std::vector<InitDeclarator*>> list;
    std::string identifier;
    FunctionParameterList parameterList;
    virtual ~InitDeclaratorList() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class InitDeclaratorList1: public InitDeclaratorList {
public:
    InitDeclarator* initDeclaratorAst1;

    InitDeclaratorList1(
        InitDeclarator* initDeclaratorAst1
    ): initDeclaratorAst1(initDeclaratorAst1) {}

    virtual ~InitDeclaratorList1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class InitDeclaratorList2: public InitDeclaratorList {
public:
    InitDeclaratorList* initDeclaratorListAst1;
    Comma* commaAst2;
    InitDeclarator* initDeclaratorAst3;

    InitDeclaratorList2(
        InitDeclaratorList* initDeclaratorListAst1,
        Comma* commaAst2,
        InitDeclarator* initDeclaratorAst3
    ): initDeclaratorListAst1(initDeclaratorListAst1), commaAst2(commaAst2), initDeclaratorAst3(initDeclaratorAst3) {}

    virtual ~InitDeclaratorList2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _INIT_DECLARATOR_LIST_H_
