// Generated by buildSrc/GenerateAST.py
#ifndef _INITIALIZER_H_
#define _INITIALIZER_H_

//#include "ast/ast.h"
class AssignmentExpression;
class Comma;
class InitializerList;
class LCurly;
class RCurly;

class Initializer: public BasicAST {
public:
    virtual ~Initializer() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class Initializer1: public Initializer {
public:
    AssignmentExpression* assignmentExpressionAst1;

    Initializer1(
        AssignmentExpression* assignmentExpressionAst1
    ): assignmentExpressionAst1(assignmentExpressionAst1) {}

    virtual ~Initializer1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class Initializer2: public Initializer {
public:
    LCurly* lCurlyAst1;
    InitializerList* initializerListAst2;
    RCurly* rCurlyAst3;

    Initializer2(
        LCurly* lCurlyAst1,
        InitializerList* initializerListAst2,
        RCurly* rCurlyAst3
    ): lCurlyAst1(lCurlyAst1), initializerListAst2(initializerListAst2), rCurlyAst3(rCurlyAst3) {}

    virtual ~Initializer2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class Initializer3: public Initializer {
public:
    LCurly* lCurlyAst1;
    InitializerList* initializerListAst2;
    Comma* commaAst3;
    RCurly* rCurlyAst4;

    Initializer3(
        LCurly* lCurlyAst1,
        InitializerList* initializerListAst2,
        Comma* commaAst3,
        RCurly* rCurlyAst4
    ): lCurlyAst1(lCurlyAst1), initializerListAst2(initializerListAst2), commaAst3(commaAst3), rCurlyAst4(rCurlyAst4) {}

    virtual ~Initializer3();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _INITIALIZER_H_
