// Generated by buildSrc/GenerateAST.py
#ifndef _INITIALIZER_LIST_H_
#define _INITIALIZER_LIST_H_

//#include "ast/ast.h"
class Comma;
class Initializer;

class InitializerList: public BasicAST {
public:
    virtual ~InitializerList() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class InitializerList1: public InitializerList {
public:
    Initializer* initializerAst1;

    InitializerList1(
        Initializer* initializerAst1
    ): initializerAst1(initializerAst1) {}

    virtual ~InitializerList1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class InitializerList2: public InitializerList {
public:
    InitializerList* initializerListAst1;
    Comma* commaAst2;
    Initializer* initializerAst3;

    InitializerList2(
        InitializerList* initializerListAst1,
        Comma* commaAst2,
        Initializer* initializerAst3
    ): initializerListAst1(initializerListAst1), commaAst2(commaAst2), initializerAst3(initializerAst3) {}

    virtual ~InitializerList2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _INITIALIZER_LIST_H_
