// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void InitDeclaratorList1::Dump(int depth) {
    TreeRender::push("InitDeclaratorList");
    initDeclaratorAst1->Dump(depth + 1);
    TreeRender::pop();
}

InitDeclaratorList1::~InitDeclaratorList1() {
    delete initDeclaratorAst1;
}

void InitDeclaratorList2::Dump(int depth) {
    TreeRender::push("InitDeclaratorList");
    initDeclaratorListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    initDeclaratorAst3->Dump(depth + 1);
    TreeRender::pop();
}

InitDeclaratorList2::~InitDeclaratorList2() {
    delete initDeclaratorListAst1;
    delete commaAst2;
    delete initDeclaratorAst3;
}
