// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/decl/initializer_list.h"

void InitializerList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "InitializerList1" << std::endl;
    initializerAst1->Dump(depth + 1);
}

InitializerList1::~InitializerList1() {
    delete initializerAst1;
}

void InitializerList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "InitializerList2" << std::endl;
    initializerListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    initializerAst3->Dump(depth + 1);
}

InitializerList2::~InitializerList2() {
    delete initializerListAst1;
    delete commaAst2;
    delete initializerAst3;
}
