// Generated by buildSrc/GenerateAST.py
#ifndef _INIT_DECLARATOR_H_
#define _INIT_DECLARATOR_H_

//#include "ast/ast.h"
class Declarator;
class Eq;
class Initializer;
class DirectDeclarator;

class InitDeclarator: public BasicAST {
public:
    DirectDeclarator *directDeclarator;
    std::shared_ptr<std::vector<IRValuePtr>> initializerValue = nullptr;
public:
    virtual ~InitDeclarator() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class InitDeclarator1: public InitDeclarator {
public:
    Declarator* declaratorAst1;

    InitDeclarator1(
        Declarator* declaratorAst1
    ): declaratorAst1(declaratorAst1) {}

    virtual ~InitDeclarator1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class InitDeclarator2: public InitDeclarator {
public:
    Declarator* declaratorAst1;
    Eq* eqAst2;
    Initializer* initializerAst3;

    InitDeclarator2(
        Declarator* declaratorAst1,
        Eq* eqAst2,
        Initializer* initializerAst3
    ): declaratorAst1(declaratorAst1), eqAst2(eqAst2), initializerAst3(initializerAst3) {}

    virtual ~InitDeclarator2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _INIT_DECLARATOR_H_
