// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void ParameterList1::Dump(int depth) {
    TreeRender::push("ParameterList");
    parameterDeclarationAst1->Dump(depth + 1);
    TreeRender::pop();
}

ParameterList1::~ParameterList1() {
    delete parameterDeclarationAst1;
}

void ParameterList2::Dump(int depth) {
    TreeRender::push("ParameterList");
    parameterListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    parameterDeclarationAst3->Dump(depth + 1);
    TreeRender::pop();
}

ParameterList2::~ParameterList2() {
    delete parameterListAst1;
    delete commaAst2;
    delete parameterDeclarationAst3;
}
