// Generated by buildSrc/GenerateAST.py
#ifndef _PARAMETER_DECLARATION_H_
#define _PARAMETER_DECLARATION_H_

#include "ast/ast.h"
//#header

class ParameterDeclaration: public BasicAST {
public:
    virtual ~ParameterDeclaration() {}
    virtual void GenerateIR(Context context) {}
    virtual void Dump(int depth) {}
};

class ParameterDeclaration1: public ParameterDeclaration {
public:
    DeclarationSpecifiers* declarationSpecifiersAst1;
    Declarator* declaratorAst2;

    ParameterDeclaration1(
        DeclarationSpecifiers* declarationSpecifiersAst1,
        Declarator* declaratorAst2
    ): declarationSpecifiersAst1(declarationSpecifiersAst1), declaratorAst2(declaratorAst2) {}

    virtual ~ParameterDeclaration1();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class ParameterDeclaration2: public ParameterDeclaration {
public:
    DeclarationSpecifiers* declarationSpecifiersAst1;
    AbstractDeclarator* abstractDeclaratorAst2;

    ParameterDeclaration2(
        DeclarationSpecifiers* declarationSpecifiersAst1,
        AbstractDeclarator* abstractDeclaratorAst2
    ): declarationSpecifiersAst1(declarationSpecifiersAst1), abstractDeclaratorAst2(abstractDeclaratorAst2) {}

    virtual ~ParameterDeclaration2();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};

class ParameterDeclaration3: public ParameterDeclaration {
public:
    DeclarationSpecifiers* declarationSpecifiersAst1;

    ParameterDeclaration3(
        DeclarationSpecifiers* declarationSpecifiersAst1
    ): declarationSpecifiersAst1(declarationSpecifiersAst1) {}

    virtual ~ParameterDeclaration3();
    virtual void GenerateIR(Context context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_DECLARATIONSPECIFIERS_
#define _CLASS_DECLARATIONSPECIFIERS_
class DeclarationSpecifiers;
#endif //_CLASS_DECLARATIONSPECIFIERS_
#ifndef _CLASS_ABSTRACTDECLARATOR_
#define _CLASS_ABSTRACTDECLARATOR_
class AbstractDeclarator;
#endif //_CLASS_ABSTRACTDECLARATOR_
#ifndef _CLASS_DECLARATOR_
#define _CLASS_DECLARATOR_
class Declarator;
#endif //_CLASS_DECLARATOR_

#endif // _PARAMETER_DECLARATION_H_
