// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ParameterDeclaration1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ParameterDeclaration1" << std::endl;
    declarationSpecifiersAst1->Dump(depth + 1);
    declaratorAst2->Dump(depth + 1);
}

ParameterDeclaration1::~ParameterDeclaration1() {
    delete declarationSpecifiersAst1;
    delete declaratorAst2;
}

void ParameterDeclaration2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ParameterDeclaration2" << std::endl;
    declarationSpecifiersAst1->Dump(depth + 1);
    abstractDeclaratorAst2->Dump(depth + 1);
}

ParameterDeclaration2::~ParameterDeclaration2() {
    delete declarationSpecifiersAst1;
    delete abstractDeclaratorAst2;
}

void ParameterDeclaration3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ParameterDeclaration3" << std::endl;
    declarationSpecifiersAst1->Dump(depth + 1);
}

ParameterDeclaration3::~ParameterDeclaration3() {
    delete declarationSpecifiersAst1;
}
