// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void ParameterDeclaration1::Dump(int depth) {
    TreeRender::push("ParameterDeclaration");
    declarationSpecifiersAst1->Dump(depth + 1);
    declaratorAst2->Dump(depth + 1);
    TreeRender::pop();
}

ParameterDeclaration1::~ParameterDeclaration1() {
    delete declarationSpecifiersAst1;
    delete declaratorAst2;
}

void ParameterDeclaration2::Dump(int depth) {
    TreeRender::push("ParameterDeclaration");
    declarationSpecifiersAst1->Dump(depth + 1);
    abstractDeclaratorAst2->Dump(depth + 1);
    TreeRender::pop();
}

ParameterDeclaration2::~ParameterDeclaration2() {
    delete declarationSpecifiersAst1;
    delete abstractDeclaratorAst2;
}

void ParameterDeclaration3::Dump(int depth) {
    TreeRender::push("ParameterDeclaration");
    declarationSpecifiersAst1->Dump(depth + 1);
    TreeRender::pop();
}

ParameterDeclaration3::~ParameterDeclaration3() {
    delete declarationSpecifiersAst1;
}
