// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ParameterTypeList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ParameterTypeList1" << std::endl;
    parameterListAst1->Dump(depth + 1);
}

ParameterTypeList1::~ParameterTypeList1() {
    delete parameterListAst1;
}

void ParameterTypeList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ParameterTypeList2" << std::endl;
    parameterListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    ellipsisAst3->Dump(depth + 1);
}

ParameterTypeList2::~ParameterTypeList2() {
    delete parameterListAst1;
    delete commaAst2;
    delete ellipsisAst3;
}
