// Generated by buildSrc/GenerateAST.py
#ifndef _PARAMETER_TYPE_LIST_H_
#define _PARAMETER_TYPE_LIST_H_

#include "ast/ast.h"
//#header

class ParameterTypeList: public BasicAST {
public:
    virtual ~ParameterTypeList() {}
    virtual void GenerateIR(Context& context) {}
    virtual void Dump(int depth) {}
};

class ParameterTypeList1: public ParameterTypeList {
public:
    ParameterList* parameterListAst1;

    ParameterTypeList1(
        ParameterList* parameterListAst1
    ): parameterListAst1(parameterListAst1) {}

    virtual ~ParameterTypeList1();
    virtual void GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class ParameterTypeList2: public ParameterTypeList {
public:
    ParameterList* parameterListAst1;
    Comma* commaAst2;
    Ellipsis* ellipsisAst3;

    ParameterTypeList2(
        ParameterList* parameterListAst1,
        Comma* commaAst2,
        Ellipsis* ellipsisAst3
    ): parameterListAst1(parameterListAst1), commaAst2(commaAst2), ellipsisAst3(ellipsisAst3) {}

    virtual ~ParameterTypeList2();
    virtual void GenerateIR(Context& context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_PARAMETERLIST_
#define _CLASS_PARAMETERLIST_
class ParameterList;
#endif //_CLASS_PARAMETERLIST_
#ifndef _CLASS_ELLIPSIS_
#define _CLASS_ELLIPSIS_
class Ellipsis;
#endif //_CLASS_ELLIPSIS_
#ifndef _CLASS_COMMA_
#define _CLASS_COMMA_
class Comma;
#endif //_CLASS_COMMA_

#endif // _PARAMETER_TYPE_LIST_H_
