// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void Pointer1::Dump(int depth) {
    TreeRender::push("Pointer");
    mulAst1->Dump(depth + 1);
    TreeRender::pop();
}

Pointer1::~Pointer1() {
    delete mulAst1;
}

void Pointer2::Dump(int depth) {
    TreeRender::push("Pointer");
    mulAst1->Dump(depth + 1);
    typeQualifierListAst2->Dump(depth + 1);
    TreeRender::pop();
}

Pointer2::~Pointer2() {
    delete mulAst1;
    delete typeQualifierListAst2;
}

void Pointer3::Dump(int depth) {
    TreeRender::push("Pointer");
    mulAst1->Dump(depth + 1);
    pointerAst2->Dump(depth + 1);
    TreeRender::pop();
}

Pointer3::~Pointer3() {
    delete mulAst1;
    delete pointerAst2;
}

void Pointer4::Dump(int depth) {
    TreeRender::push("Pointer");
    mulAst1->Dump(depth + 1);
    typeQualifierListAst2->Dump(depth + 1);
    pointerAst3->Dump(depth + 1);
    TreeRender::pop();
}

Pointer4::~Pointer4() {
    delete mulAst1;
    delete typeQualifierListAst2;
    delete pointerAst3;
}
