// Generated by buildSrc/GenerateAST.py
#ifndef _POINTER_H_
#define _POINTER_H_

#include "ast/ast.h"
//#header

class Pointer: public BasicAST {
public:
    virtual ~Pointer() {}
    virtual void GenerateIR(Context& context) {}
    virtual void Dump(int depth) {}
};

class Pointer1: public Pointer {
public:
    Mul* mulAst1;

    Pointer1(
        Mul* mulAst1
    ): mulAst1(mulAst1) {}

    virtual ~Pointer1();
    virtual void GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class Pointer2: public Pointer {
public:
    Mul* mulAst1;
    TypeQualifierList* typeQualifierListAst2;

    Pointer2(
        Mul* mulAst1,
        TypeQualifierList* typeQualifierListAst2
    ): mulAst1(mulAst1), typeQualifierListAst2(typeQualifierListAst2) {}

    virtual ~Pointer2();
    virtual void GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class Pointer3: public Pointer {
public:
    Mul* mulAst1;
    Pointer* pointerAst2;

    Pointer3(
        Mul* mulAst1,
        Pointer* pointerAst2
    ): mulAst1(mulAst1), pointerAst2(pointerAst2) {}

    virtual ~Pointer3();
    virtual void GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class Pointer4: public Pointer {
public:
    Mul* mulAst1;
    TypeQualifierList* typeQualifierListAst2;
    Pointer* pointerAst3;

    Pointer4(
        Mul* mulAst1,
        TypeQualifierList* typeQualifierListAst2,
        Pointer* pointerAst3
    ): mulAst1(mulAst1), typeQualifierListAst2(typeQualifierListAst2), pointerAst3(pointerAst3) {}

    virtual ~Pointer4();
    virtual void GenerateIR(Context& context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_MUL_
#define _CLASS_MUL_
class Mul;
#endif //_CLASS_MUL_
#ifndef _CLASS_TYPEQUALIFIERLIST_
#define _CLASS_TYPEQUALIFIERLIST_
class TypeQualifierList;
#endif //_CLASS_TYPEQUALIFIERLIST_

#endif // _POINTER_H_
