// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/decl/specifier_qualifier_list.h"

void SpecifierQualifierList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "SpecifierQualifierList1" << std::endl;
    typeSpecifierAst1->Dump(depth + 1);
    specifierQualifierListAst2->Dump(depth + 1);
}

SpecifierQualifierList1::~SpecifierQualifierList1() {
    delete typeSpecifierAst1;
    delete specifierQualifierListAst2;
}

void SpecifierQualifierList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "SpecifierQualifierList2" << std::endl;
    typeSpecifierAst1->Dump(depth + 1);
}

SpecifierQualifierList2::~SpecifierQualifierList2() {
    delete typeSpecifierAst1;
}

void SpecifierQualifierList3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "SpecifierQualifierList3" << std::endl;
    typeQualifierAst1->Dump(depth + 1);
    specifierQualifierListAst2->Dump(depth + 1);
}

SpecifierQualifierList3::~SpecifierQualifierList3() {
    delete typeQualifierAst1;
    delete specifierQualifierListAst2;
}

void SpecifierQualifierList4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "SpecifierQualifierList4" << std::endl;
    typeQualifierAst1->Dump(depth + 1);
}

SpecifierQualifierList4::~SpecifierQualifierList4() {
    delete typeQualifierAst1;
}
