// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void SpecifierQualifierList1::Dump(int depth) {
    TreeRender::push("SpecifierQualifierList");
    typeSpecifierAst1->Dump(depth + 1);
    specifierQualifierListAst2->Dump(depth + 1);
    TreeRender::pop();
}

SpecifierQualifierList1::~SpecifierQualifierList1() {
    delete typeSpecifierAst1;
    delete specifierQualifierListAst2;
}

void SpecifierQualifierList2::Dump(int depth) {
    TreeRender::push("SpecifierQualifierList");
    typeSpecifierAst1->Dump(depth + 1);
    TreeRender::pop();
}

SpecifierQualifierList2::~SpecifierQualifierList2() {
    delete typeSpecifierAst1;
}

void SpecifierQualifierList3::Dump(int depth) {
    TreeRender::push("SpecifierQualifierList");
    typeQualifierAst1->Dump(depth + 1);
    specifierQualifierListAst2->Dump(depth + 1);
    TreeRender::pop();
}

SpecifierQualifierList3::~SpecifierQualifierList3() {
    delete typeQualifierAst1;
    delete specifierQualifierListAst2;
}

void SpecifierQualifierList4::Dump(int depth) {
    TreeRender::push("SpecifierQualifierList");
    typeQualifierAst1->Dump(depth + 1);
    TreeRender::pop();
}

SpecifierQualifierList4::~SpecifierQualifierList4() {
    delete typeQualifierAst1;
}
