// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void StorageClassSpecifier1::Dump(int depth) {
    TreeRender::push("StorageClassSpecifier");
    typedefAst1->Dump(depth + 1);
    TreeRender::pop();
}

StorageClassSpecifier1::~StorageClassSpecifier1() {
    delete typedefAst1;
}

void StorageClassSpecifier2::Dump(int depth) {
    TreeRender::push("StorageClassSpecifier");
    externAst1->Dump(depth + 1);
    TreeRender::pop();
}

StorageClassSpecifier2::~StorageClassSpecifier2() {
    delete externAst1;
}

void StorageClassSpecifier3::Dump(int depth) {
    TreeRender::push("StorageClassSpecifier");
    staticAst1->Dump(depth + 1);
    TreeRender::pop();
}

StorageClassSpecifier3::~StorageClassSpecifier3() {
    delete staticAst1;
}

void StorageClassSpecifier4::Dump(int depth) {
    TreeRender::push("StorageClassSpecifier");
    autoAst1->Dump(depth + 1);
    TreeRender::pop();
}

StorageClassSpecifier4::~StorageClassSpecifier4() {
    delete autoAst1;
}

void StorageClassSpecifier5::Dump(int depth) {
    TreeRender::push("StorageClassSpecifier");
    registerAst1->Dump(depth + 1);
    TreeRender::pop();
}

StorageClassSpecifier5::~StorageClassSpecifier5() {
    delete registerAst1;
}
