// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void StorageClassSpecifier1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StorageClassSpecifier1" << std::endl;
    typedefAst1->Dump(depth + 1);
}

StorageClassSpecifier1::~StorageClassSpecifier1() {
    delete typedefAst1;
}

void StorageClassSpecifier2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StorageClassSpecifier2" << std::endl;
    externAst1->Dump(depth + 1);
}

StorageClassSpecifier2::~StorageClassSpecifier2() {
    delete externAst1;
}

void StorageClassSpecifier3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StorageClassSpecifier3" << std::endl;
    staticAst1->Dump(depth + 1);
}

StorageClassSpecifier3::~StorageClassSpecifier3() {
    delete staticAst1;
}

void StorageClassSpecifier4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StorageClassSpecifier4" << std::endl;
    autoAst1->Dump(depth + 1);
}

StorageClassSpecifier4::~StorageClassSpecifier4() {
    delete autoAst1;
}

void StorageClassSpecifier5::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StorageClassSpecifier5" << std::endl;
    registerAst1->Dump(depth + 1);
}

StorageClassSpecifier5::~StorageClassSpecifier5() {
    delete registerAst1;
}
