// Generated by buildSrc/GenerateAST.py
#ifndef _STRUCT_OR_UNION_H_
#define _STRUCT_OR_UNION_H_

//#include "ast/ast.h"
class Struct;
class Union;

class StructOrUnion: public BasicAST {
public:
    virtual ~StructOrUnion() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class StructOrUnion1: public StructOrUnion {
public:
    Struct* structAst1;

    StructOrUnion1(
        Struct* structAst1
    ): structAst1(structAst1) {}

    virtual ~StructOrUnion1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class StructOrUnion2: public StructOrUnion {
public:
    Union* unionAst1;

    StructOrUnion2(
        Union* unionAst1
    ): unionAst1(unionAst1) {}

    virtual ~StructOrUnion2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _STRUCT_OR_UNION_H_
