// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void StructDeclaratorList1::Dump(int depth) {
    TreeRender::push("StructDeclaratorList");
    structDeclaratorAst1->Dump(depth + 1);
    TreeRender::pop();
}

StructDeclaratorList1::~StructDeclaratorList1() {
    delete structDeclaratorAst1;
}

void StructDeclaratorList2::Dump(int depth) {
    TreeRender::push("StructDeclaratorList");
    structDeclaratorListAst1->Dump(depth + 1);
    commaAst2->Dump(depth + 1);
    structDeclaratorAst3->Dump(depth + 1);
    TreeRender::pop();
}

StructDeclaratorList2::~StructDeclaratorList2() {
    delete structDeclaratorListAst1;
    delete commaAst2;
    delete structDeclaratorAst3;
}
