// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/decl/struct_declarator.h"

void StructDeclarator1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StructDeclarator1" << std::endl;
    declaratorAst1->Dump(depth + 1);
}

StructDeclarator1::~StructDeclarator1() {
    delete declaratorAst1;
}

void StructDeclarator2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StructDeclarator2" << std::endl;
    colonAst1->Dump(depth + 1);
    constantExpressionAst2->Dump(depth + 1);
}

StructDeclarator2::~StructDeclarator2() {
    delete colonAst1;
    delete constantExpressionAst2;
}

void StructDeclarator3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StructDeclarator3" << std::endl;
    declaratorAst1->Dump(depth + 1);
    colonAst2->Dump(depth + 1);
    constantExpressionAst3->Dump(depth + 1);
}

StructDeclarator3::~StructDeclarator3() {
    delete declaratorAst1;
    delete colonAst2;
    delete constantExpressionAst3;
}
