// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void StructDeclarator1::Dump(int depth) {
    TreeRender::push("StructDeclarator");
    declaratorAst1->Dump(depth + 1);
    TreeRender::pop();
}

StructDeclarator1::~StructDeclarator1() {
    delete declaratorAst1;
}

void StructDeclarator2::Dump(int depth) {
    TreeRender::push("StructDeclarator");
    colonAst1->Dump(depth + 1);
    constantExpressionAst2->Dump(depth + 1);
    TreeRender::pop();
}

StructDeclarator2::~StructDeclarator2() {
    delete colonAst1;
    delete constantExpressionAst2;
}

void StructDeclarator3::Dump(int depth) {
    TreeRender::push("StructDeclarator");
    declaratorAst1->Dump(depth + 1);
    colonAst2->Dump(depth + 1);
    constantExpressionAst3->Dump(depth + 1);
    TreeRender::pop();
}

StructDeclarator3::~StructDeclarator3() {
    delete declaratorAst1;
    delete colonAst2;
    delete constantExpressionAst3;
}
