// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void StructDeclaration1::Dump(int depth) {
    TreeRender::push("StructDeclaration");
    specifierQualifierListAst1->Dump(depth + 1);
    structDeclaratorListAst2->Dump(depth + 1);
    simicolonSingleAst3->Dump(depth + 1);
    TreeRender::pop();
}

StructDeclaration1::~StructDeclaration1() {
    delete specifierQualifierListAst1;
    delete structDeclaratorListAst2;
    delete simicolonSingleAst3;
}
