// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void StructOrUnion1::Dump(int depth) {
    TreeRender::push("StructOrUnion");
    structAst1->Dump(depth + 1);
    TreeRender::pop();
}

StructOrUnion1::~StructOrUnion1() {
    delete structAst1;
}

void StructOrUnion2::Dump(int depth) {
    TreeRender::push("StructOrUnion");
    unionAst1->Dump(depth + 1);
    TreeRender::pop();
}

StructOrUnion2::~StructOrUnion2() {
    delete unionAst1;
}
