// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void StructOrUnionSpecifier1::Dump(int depth) {
    TreeRender::push("StructOrUnionSpecifier");
    structOrUnionAst1->Dump(depth + 1);
    identifierAst2->Dump(depth + 1);
    lCurlyAst3->Dump(depth + 1);
    structDeclarationListAst4->Dump(depth + 1);
    rCurlyAst5->Dump(depth + 1);
    TreeRender::pop();
}

StructOrUnionSpecifier1::~StructOrUnionSpecifier1() {
    delete structOrUnionAst1;
    delete identifierAst2;
    delete lCurlyAst3;
    delete structDeclarationListAst4;
    delete rCurlyAst5;
}

void StructOrUnionSpecifier2::Dump(int depth) {
    TreeRender::push("StructOrUnionSpecifier");
    structOrUnionAst1->Dump(depth + 1);
    lCurlyAst2->Dump(depth + 1);
    structDeclarationListAst3->Dump(depth + 1);
    rCurlyAst4->Dump(depth + 1);
    TreeRender::pop();
}

StructOrUnionSpecifier2::~StructOrUnionSpecifier2() {
    delete structOrUnionAst1;
    delete lCurlyAst2;
    delete structDeclarationListAst3;
    delete rCurlyAst4;
}

void StructOrUnionSpecifier3::Dump(int depth) {
    TreeRender::push("StructOrUnionSpecifier");
    structOrUnionAst1->Dump(depth + 1);
    identifierAst2->Dump(depth + 1);
    TreeRender::pop();
}

StructOrUnionSpecifier3::~StructOrUnionSpecifier3() {
    delete structOrUnionAst1;
    delete identifierAst2;
}
