// Generated by buildSrc/GenerateAST.py
#ifndef _STRUCT_DECLARATION_H_
#define _STRUCT_DECLARATION_H_

//#include "ast/ast.h"
class SimicolonSingle;
class SpecifierQualifierList;
class StructDeclaratorList;

class StructDeclaration: public BasicAST {
public:
    virtual ~StructDeclaration() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class StructDeclaration1: public StructDeclaration {
public:
    SpecifierQualifierList* specifierQualifierListAst1;
    StructDeclaratorList* structDeclaratorListAst2;
    SimicolonSingle* simicolonSingleAst3;

    StructDeclaration1(
        SpecifierQualifierList* specifierQualifierListAst1,
        StructDeclaratorList* structDeclaratorListAst2,
        SimicolonSingle* simicolonSingleAst3
    ): specifierQualifierListAst1(specifierQualifierListAst1), structDeclaratorListAst2(structDeclaratorListAst2), simicolonSingleAst3(simicolonSingleAst3) {}

    virtual ~StructDeclaration1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _STRUCT_DECLARATION_H_
