// Generated by buildSrc/GenerateAST.py
#ifndef _TYPE_QUALIFIER_LIST_H_
#define _TYPE_QUALIFIER_LIST_H_

//#include "ast/ast.h"
class TypeQualifier;

class TypeQualifierList: public BasicAST {
public:
    virtual ~TypeQualifierList() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class TypeQualifierList1: public TypeQualifierList {
public:
    TypeQualifier* typeQualifierAst1;

    TypeQualifierList1(
        TypeQualifier* typeQualifierAst1
    ): typeQualifierAst1(typeQualifierAst1) {}

    virtual ~TypeQualifierList1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class TypeQualifierList2: public TypeQualifierList {
public:
    TypeQualifierList* typeQualifierListAst1;
    TypeQualifier* typeQualifierAst2;

    TypeQualifierList2(
        TypeQualifierList* typeQualifierListAst1,
        TypeQualifier* typeQualifierAst2
    ): typeQualifierListAst1(typeQualifierListAst1), typeQualifierAst2(typeQualifierAst2) {}

    virtual ~TypeQualifierList2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _TYPE_QUALIFIER_LIST_H_
