// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void TypeName1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "TypeName1" << std::endl;
    specifierQualifierListAst1->Dump(depth + 1);
}

TypeName1::~TypeName1() {
    delete specifierQualifierListAst1;
}

void TypeName2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "TypeName2" << std::endl;
    specifierQualifierListAst1->Dump(depth + 1);
    abstractDeclaratorAst2->Dump(depth + 1);
}

TypeName2::~TypeName2() {
    delete specifierQualifierListAst1;
    delete abstractDeclaratorAst2;
}
