// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void TypeSpecifier1::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    voidAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier1::~TypeSpecifier1() {
    delete voidAst1;
}

void TypeSpecifier2::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    charAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier2::~TypeSpecifier2() {
    delete charAst1;
}

void TypeSpecifier3::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    shortAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier3::~TypeSpecifier3() {
    delete shortAst1;
}

void TypeSpecifier4::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    intAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier4::~TypeSpecifier4() {
    delete intAst1;
}

void TypeSpecifier5::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    longAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier5::~TypeSpecifier5() {
    delete longAst1;
}

void TypeSpecifier6::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    floatAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier6::~TypeSpecifier6() {
    delete floatAst1;
}

void TypeSpecifier7::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    doubleAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier7::~TypeSpecifier7() {
    delete doubleAst1;
}

void TypeSpecifier8::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    signedAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier8::~TypeSpecifier8() {
    delete signedAst1;
}

void TypeSpecifier9::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    unsignedAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier9::~TypeSpecifier9() {
    delete unsignedAst1;
}

void TypeSpecifier10::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    structOrUnionSpecifierAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier10::~TypeSpecifier10() {
    delete structOrUnionSpecifierAst1;
}

void TypeSpecifier11::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    enumSpecifierAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier11::~TypeSpecifier11() {
    delete enumSpecifierAst1;
}

void TypeSpecifier12::Dump(int depth) {
    TreeRender::push("TypeSpecifier");
    typeNameTokenAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeSpecifier12::~TypeSpecifier12() {
    delete typeNameTokenAst1;
}
