// Generated by buildSrc/GenerateAST.py
#ifndef _TYPE_QUALIFIER_H_
#define _TYPE_QUALIFIER_H_

//#include "ast/ast.h"
class Const;
class Volatile;

class TypeQualifier: public BasicAST {
public:
    virtual ~TypeQualifier() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class TypeQualifier1: public TypeQualifier {
public:
    Const* constAst1;

    TypeQualifier1(
        Const* constAst1
    ): constAst1(constAst1) {}

    virtual ~TypeQualifier1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class TypeQualifier2: public TypeQualifier {
public:
    Volatile* volatileAst1;

    TypeQualifier2(
        Volatile* volatileAst1
    ): volatileAst1(volatileAst1) {}

    virtual ~TypeQualifier2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _TYPE_QUALIFIER_H_
