// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void TypeName1::Dump(int depth) {
    TreeRender::push("TypeName");
    specifierQualifierListAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeName1::~TypeName1() {
    delete specifierQualifierListAst1;
}

void TypeName2::Dump(int depth) {
    TreeRender::push("TypeName");
    specifierQualifierListAst1->Dump(depth + 1);
    abstractDeclaratorAst2->Dump(depth + 1);
    TreeRender::pop();
}

TypeName2::~TypeName2() {
    delete specifierQualifierListAst1;
    delete abstractDeclaratorAst2;
}
