// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/decl/type_qualifier.h"

void TypeQualifier1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "TypeQualifier1" << std::endl;
    constAst1->Dump(depth + 1);
}

TypeQualifier1::~TypeQualifier1() {
    delete constAst1;
}

void TypeQualifier2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "TypeQualifier2" << std::endl;
    volatileAst1->Dump(depth + 1);
}

TypeQualifier2::~TypeQualifier2() {
    delete volatileAst1;
}
