// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void TypeQualifierList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "TypeQualifierList1" << std::endl;
    typeQualifierAst1->Dump(depth + 1);
}

TypeQualifierList1::~TypeQualifierList1() {
    delete typeQualifierAst1;
}

void TypeQualifierList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "TypeQualifierList2" << std::endl;
    typeQualifierListAst1->Dump(depth + 1);
    typeQualifierAst2->Dump(depth + 1);
}

TypeQualifierList2::~TypeQualifierList2() {
    delete typeQualifierListAst1;
    delete typeQualifierAst2;
}
