// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void TypeQualifierList1::Dump(int depth) {
    TreeRender::push("TypeQualifierList");
    typeQualifierAst1->Dump(depth + 1);
    TreeRender::pop();
}

TypeQualifierList1::~TypeQualifierList1() {
    delete typeQualifierAst1;
}

void TypeQualifierList2::Dump(int depth) {
    TreeRender::push("TypeQualifierList");
    typeQualifierListAst1->Dump(depth + 1);
    typeQualifierAst2->Dump(depth + 1);
    TreeRender::pop();
}

TypeQualifierList2::~TypeQualifierList2() {
    delete typeQualifierListAst1;
    delete typeQualifierAst2;
}
