// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/statement/compound_statement.h"

void CompoundStatement1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "CompoundStatement1" << std::endl;
    lCurlyAst1->Dump(depth + 1);
    rCurlyAst2->Dump(depth + 1);
}

CompoundStatement1::~CompoundStatement1() {
    delete lCurlyAst1;
    delete rCurlyAst2;
}

void CompoundStatement2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "CompoundStatement2" << std::endl;
    lCurlyAst1->Dump(depth + 1);
    statementListAst2->Dump(depth + 1);
    rCurlyAst3->Dump(depth + 1);
}

CompoundStatement2::~CompoundStatement2() {
    delete lCurlyAst1;
    delete statementListAst2;
    delete rCurlyAst3;
}

void CompoundStatement3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "CompoundStatement3" << std::endl;
    lCurlyAst1->Dump(depth + 1);
    declarationListAst2->Dump(depth + 1);
    rCurlyAst3->Dump(depth + 1);
}

CompoundStatement3::~CompoundStatement3() {
    delete lCurlyAst1;
    delete declarationListAst2;
    delete rCurlyAst3;
}

void CompoundStatement4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "CompoundStatement4" << std::endl;
    lCurlyAst1->Dump(depth + 1);
    declarationListAst2->Dump(depth + 1);
    statementListAst3->Dump(depth + 1);
    rCurlyAst4->Dump(depth + 1);
}

CompoundStatement4::~CompoundStatement4() {
    delete lCurlyAst1;
    delete declarationListAst2;
    delete statementListAst3;
    delete rCurlyAst4;
}
