// Generated by buildSrc/GenerateAST.py
#ifndef _COMPOUND_STATEMENT_H_
#define _COMPOUND_STATEMENT_H_

//#include "ast/ast.h"
class DeclarationList;
class LCurly;
class RCurly;
class StatementList;

class CompoundStatement: public BasicAST {
public:
    virtual ~CompoundStatement() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class CompoundStatement1: public CompoundStatement {
public:
    LCurly* lCurlyAst1;
    RCurly* rCurlyAst2;

    CompoundStatement1(
        LCurly* lCurlyAst1,
        RCurly* rCurlyAst2
    ): lCurlyAst1(lCurlyAst1), rCurlyAst2(rCurlyAst2) {}

    virtual ~CompoundStatement1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class CompoundStatement2: public CompoundStatement {
public:
    LCurly* lCurlyAst1;
    StatementList* statementListAst2;
    RCurly* rCurlyAst3;

    CompoundStatement2(
        LCurly* lCurlyAst1,
        StatementList* statementListAst2,
        RCurly* rCurlyAst3
    ): lCurlyAst1(lCurlyAst1), statementListAst2(statementListAst2), rCurlyAst3(rCurlyAst3) {}

    virtual ~CompoundStatement2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class CompoundStatement3: public CompoundStatement {
public:
    LCurly* lCurlyAst1;
    DeclarationList* declarationListAst2;
    RCurly* rCurlyAst3;

    CompoundStatement3(
        LCurly* lCurlyAst1,
        DeclarationList* declarationListAst2,
        RCurly* rCurlyAst3
    ): lCurlyAst1(lCurlyAst1), declarationListAst2(declarationListAst2), rCurlyAst3(rCurlyAst3) {}

    virtual ~CompoundStatement3();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class CompoundStatement4: public CompoundStatement {
public:
    LCurly* lCurlyAst1;
    DeclarationList* declarationListAst2;
    StatementList* statementListAst3;
    RCurly* rCurlyAst4;

    CompoundStatement4(
        LCurly* lCurlyAst1,
        DeclarationList* declarationListAst2,
        StatementList* statementListAst3,
        RCurly* rCurlyAst4
    ): lCurlyAst1(lCurlyAst1), declarationListAst2(declarationListAst2), statementListAst3(statementListAst3), rCurlyAst4(rCurlyAst4) {}

    virtual ~CompoundStatement4();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _COMPOUND_STATEMENT_H_
