// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void CompoundStatement1::Dump(int depth) {
    TreeRender::push("CompoundStatement");
    lCurlyAst1->Dump(depth + 1);
    rCurlyAst2->Dump(depth + 1);
    TreeRender::pop();
}

CompoundStatement1::~CompoundStatement1() {
    delete lCurlyAst1;
    delete rCurlyAst2;
}

void CompoundStatement2::Dump(int depth) {
    TreeRender::push("CompoundStatement");
    lCurlyAst1->Dump(depth + 1);
    statementListAst2->Dump(depth + 1);
    rCurlyAst3->Dump(depth + 1);
    TreeRender::pop();
}

CompoundStatement2::~CompoundStatement2() {
    delete lCurlyAst1;
    delete statementListAst2;
    delete rCurlyAst3;
}

void CompoundStatement3::Dump(int depth) {
    TreeRender::push("CompoundStatement");
    lCurlyAst1->Dump(depth + 1);
    declarationListAst2->Dump(depth + 1);
    rCurlyAst3->Dump(depth + 1);
    TreeRender::pop();
}

CompoundStatement3::~CompoundStatement3() {
    delete lCurlyAst1;
    delete declarationListAst2;
    delete rCurlyAst3;
}

void CompoundStatement4::Dump(int depth) {
    TreeRender::push("CompoundStatement");
    lCurlyAst1->Dump(depth + 1);
    declarationListAst2->Dump(depth + 1);
    statementListAst3->Dump(depth + 1);
    rCurlyAst4->Dump(depth + 1);
    TreeRender::pop();
}

CompoundStatement4::~CompoundStatement4() {
    delete lCurlyAst1;
    delete declarationListAst2;
    delete statementListAst3;
    delete rCurlyAst4;
}
