// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void DeclarationList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "DeclarationList1" << std::endl;
    declarationAst1->Dump(depth + 1);
}

DeclarationList1::~DeclarationList1() {
    delete declarationAst1;
}

void DeclarationList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "DeclarationList2" << std::endl;
    declarationListAst1->Dump(depth + 1);
    declarationAst2->Dump(depth + 1);
}

DeclarationList2::~DeclarationList2() {
    delete declarationListAst1;
    delete declarationAst2;
}
