// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void DeclarationList1::Dump(int depth) {
    TreeRender::push("DeclarationList");
    declarationAst1->Dump(depth + 1);
    TreeRender::pop();
}

DeclarationList1::~DeclarationList1() {
    delete declarationAst1;
}

void DeclarationList2::Dump(int depth) {
    TreeRender::push("DeclarationList");
    declarationListAst1->Dump(depth + 1);
    declarationAst2->Dump(depth + 1);
    TreeRender::pop();
}

DeclarationList2::~DeclarationList2() {
    delete declarationListAst1;
    delete declarationAst2;
}
