// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ExpressionStatement1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ExpressionStatement1" << std::endl;
    simicolonSingleAst1->Dump(depth + 1);
}

ExpressionStatement1::~ExpressionStatement1() {
    delete simicolonSingleAst1;
}

void ExpressionStatement2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ExpressionStatement2" << std::endl;
    expressionAst1->Dump(depth + 1);
    simicolonSingleAst2->Dump(depth + 1);
}

ExpressionStatement2::~ExpressionStatement2() {
    delete expressionAst1;
    delete simicolonSingleAst2;
}
