// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void ExpressionStatement1::Dump(int depth) {
    TreeRender::push("ExpressionStatement");
    simicolonSingleAst1->Dump(depth + 1);
    TreeRender::pop();
}

ExpressionStatement1::~ExpressionStatement1() {
    delete simicolonSingleAst1;
}

void ExpressionStatement2::Dump(int depth) {
    TreeRender::push("ExpressionStatement");
    expressionAst1->Dump(depth + 1);
    simicolonSingleAst2->Dump(depth + 1);
    TreeRender::pop();
}

ExpressionStatement2::~ExpressionStatement2() {
    delete expressionAst1;
    delete simicolonSingleAst2;
}
