// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void ExternalDeclaration1::Dump(int depth) {
    TreeRender::push("ExternalDeclaration");
    functionDefinitionAst1->Dump(depth + 1);
    TreeRender::pop();
}

ExternalDeclaration1::~ExternalDeclaration1() {
    delete functionDefinitionAst1;
}

void ExternalDeclaration2::Dump(int depth) {
    TreeRender::push("ExternalDeclaration");
    declarationAst1->Dump(depth + 1);
    TreeRender::pop();
}

ExternalDeclaration2::~ExternalDeclaration2() {
    delete declarationAst1;
}
