// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void ExternalDeclaration1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ExternalDeclaration1" << std::endl;
    functionDefinitionAst1->Dump(depth + 1);
}

ExternalDeclaration1::~ExternalDeclaration1() {
    delete functionDefinitionAst1;
}

void ExternalDeclaration2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "ExternalDeclaration2" << std::endl;
    declarationAst1->Dump(depth + 1);
}

ExternalDeclaration2::~ExternalDeclaration2() {
    delete declarationAst1;
}
