// Generated by buildSrc/GenerateAST.py
#ifndef _EXTERNAL_DECLARATION_H_
#define _EXTERNAL_DECLARATION_H_

#include "ast/ast.h"
//#header

class ExternalDeclaration: public BasicAST {
public:
    virtual ~ExternalDeclaration() {}
    virtual void GenerateIR(Context& context) {}
    virtual void Dump(int depth) {}
};

class ExternalDeclaration1: public ExternalDeclaration {
public:
    FunctionDefinition* functionDefinitionAst1;

    ExternalDeclaration1(
        FunctionDefinition* functionDefinitionAst1
    ): functionDefinitionAst1(functionDefinitionAst1) {}

    virtual ~ExternalDeclaration1();
    virtual void GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class ExternalDeclaration2: public ExternalDeclaration {
public:
    Declaration* declarationAst1;

    ExternalDeclaration2(
        Declaration* declarationAst1
    ): declarationAst1(declarationAst1) {}

    virtual ~ExternalDeclaration2();
    virtual void GenerateIR(Context& context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_FUNCTIONDEFINITION_
#define _CLASS_FUNCTIONDEFINITION_
class FunctionDefinition;
#endif //_CLASS_FUNCTIONDEFINITION_
#ifndef _CLASS_DECLARATION_
#define _CLASS_DECLARATION_
class Declaration;
#endif //_CLASS_DECLARATION_

#endif // _EXTERNAL_DECLARATION_H_
