// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void FunctionDefinition1::Dump(int depth) {
    TreeRender::push("FunctionDefinition");
    declarationSpecifiersAst1->Dump(depth + 1);
    declaratorAst2->Dump(depth + 1);
    declarationListAst3->Dump(depth + 1);
    compoundStatementAst4->Dump(depth + 1);
    TreeRender::pop();
}

FunctionDefinition1::~FunctionDefinition1() {
    delete declarationSpecifiersAst1;
    delete declaratorAst2;
    delete declarationListAst3;
    delete compoundStatementAst4;
}

void FunctionDefinition2::Dump(int depth) {
    TreeRender::push("FunctionDefinition");
    declarationSpecifiersAst1->Dump(depth + 1);
    declaratorAst2->Dump(depth + 1);
    compoundStatementAst3->Dump(depth + 1);
    TreeRender::pop();
}

FunctionDefinition2::~FunctionDefinition2() {
    delete declarationSpecifiersAst1;
    delete declaratorAst2;
    delete compoundStatementAst3;
}

void FunctionDefinition3::Dump(int depth) {
    TreeRender::push("FunctionDefinition");
    declaratorAst1->Dump(depth + 1);
    declarationListAst2->Dump(depth + 1);
    compoundStatementAst3->Dump(depth + 1);
    TreeRender::pop();
}

FunctionDefinition3::~FunctionDefinition3() {
    delete declaratorAst1;
    delete declarationListAst2;
    delete compoundStatementAst3;
}

void FunctionDefinition4::Dump(int depth) {
    TreeRender::push("FunctionDefinition");
    declaratorAst1->Dump(depth + 1);
    compoundStatementAst2->Dump(depth + 1);
    TreeRender::pop();
}

FunctionDefinition4::~FunctionDefinition4() {
    delete declaratorAst1;
    delete compoundStatementAst2;
}
