// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/statement/function_definition.h"

void FunctionDefinition1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "FunctionDefinition1" << std::endl;
    declarationSpecifiersAst1->Dump(depth + 1);
    declaratorAst2->Dump(depth + 1);
    declarationListAst3->Dump(depth + 1);
    compoundStatementAst4->Dump(depth + 1);
}

FunctionDefinition1::~FunctionDefinition1() {
    delete declarationSpecifiersAst1;
    delete declaratorAst2;
    delete declarationListAst3;
    delete compoundStatementAst4;
}

void FunctionDefinition2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "FunctionDefinition2" << std::endl;
    declarationSpecifiersAst1->Dump(depth + 1);
    declaratorAst2->Dump(depth + 1);
    compoundStatementAst3->Dump(depth + 1);
}

FunctionDefinition2::~FunctionDefinition2() {
    delete declarationSpecifiersAst1;
    delete declaratorAst2;
    delete compoundStatementAst3;
}

void FunctionDefinition3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "FunctionDefinition3" << std::endl;
    declaratorAst1->Dump(depth + 1);
    declarationListAst2->Dump(depth + 1);
    compoundStatementAst3->Dump(depth + 1);
}

FunctionDefinition3::~FunctionDefinition3() {
    delete declaratorAst1;
    delete declarationListAst2;
    delete compoundStatementAst3;
}

void FunctionDefinition4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "FunctionDefinition4" << std::endl;
    declaratorAst1->Dump(depth + 1);
    compoundStatementAst2->Dump(depth + 1);
}

FunctionDefinition4::~FunctionDefinition4() {
    delete declaratorAst1;
    delete compoundStatementAst2;
}
