// Generated by buildSrc/GenerateAST.py
#ifndef _ITERATION_STATEMENT_H_
#define _ITERATION_STATEMENT_H_

//#include "ast/ast.h"
class Do;
class Expression;
class ExpressionStatement;
class For;
class LRound;
class RRound;
class SimicolonSingle;
class Statement;
class While;

class IterationStatement: public BasicAST {
public:
    virtual ~IterationStatement() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class IterationStatement1: public IterationStatement {
public:
    While* whileAst1;
    LRound* lRoundAst2;
    Expression* expressionAst3;
    RRound* rRoundAst4;
    Statement* statementAst5;

    IterationStatement1(
        While* whileAst1,
        LRound* lRoundAst2,
        Expression* expressionAst3,
        RRound* rRoundAst4,
        Statement* statementAst5
    ): whileAst1(whileAst1), lRoundAst2(lRoundAst2), expressionAst3(expressionAst3), rRoundAst4(rRoundAst4), statementAst5(statementAst5) {}

    virtual ~IterationStatement1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class IterationStatement2: public IterationStatement {
public:
    Do* doAst1;
    Statement* statementAst2;
    While* whileAst3;
    LRound* lRoundAst4;
    Expression* expressionAst5;
    RRound* rRoundAst6;
    SimicolonSingle* simicolonSingleAst7;

    IterationStatement2(
        Do* doAst1,
        Statement* statementAst2,
        While* whileAst3,
        LRound* lRoundAst4,
        Expression* expressionAst5,
        RRound* rRoundAst6,
        SimicolonSingle* simicolonSingleAst7
    ): doAst1(doAst1), statementAst2(statementAst2), whileAst3(whileAst3), lRoundAst4(lRoundAst4), expressionAst5(expressionAst5), rRoundAst6(rRoundAst6), simicolonSingleAst7(simicolonSingleAst7) {}

    virtual ~IterationStatement2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class IterationStatement3: public IterationStatement {
public:
    For* forAst1;
    LRound* lRoundAst2;
    ExpressionStatement* expressionStatementAst3;
    ExpressionStatement* expressionStatementAst4;
    RRound* rRoundAst5;
    Statement* statementAst6;

    IterationStatement3(
        For* forAst1,
        LRound* lRoundAst2,
        ExpressionStatement* expressionStatementAst3,
        ExpressionStatement* expressionStatementAst4,
        RRound* rRoundAst5,
        Statement* statementAst6
    ): forAst1(forAst1), lRoundAst2(lRoundAst2), expressionStatementAst3(expressionStatementAst3), expressionStatementAst4(expressionStatementAst4), rRoundAst5(rRoundAst5), statementAst6(statementAst6) {}

    virtual ~IterationStatement3();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class IterationStatement4: public IterationStatement {
public:
    For* forAst1;
    LRound* lRoundAst2;
    ExpressionStatement* expressionStatementAst3;
    ExpressionStatement* expressionStatementAst4;
    Expression* expressionAst5;
    RRound* rRoundAst6;
    Statement* statementAst7;

    IterationStatement4(
        For* forAst1,
        LRound* lRoundAst2,
        ExpressionStatement* expressionStatementAst3,
        ExpressionStatement* expressionStatementAst4,
        Expression* expressionAst5,
        RRound* rRoundAst6,
        Statement* statementAst7
    ): forAst1(forAst1), lRoundAst2(lRoundAst2), expressionStatementAst3(expressionStatementAst3), expressionStatementAst4(expressionStatementAst4), expressionAst5(expressionAst5), rRoundAst6(rRoundAst6), statementAst7(statementAst7) {}

    virtual ~IterationStatement4();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _ITERATION_STATEMENT_H_
