// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void JumpStatement1::Dump(int depth) {
    TreeRender::push("JumpStatement");
    gotoAst1->Dump(depth + 1);
    identifierAst2->Dump(depth + 1);
    simicolonSingleAst3->Dump(depth + 1);
    TreeRender::pop();
}

JumpStatement1::~JumpStatement1() {
    delete gotoAst1;
    delete identifierAst2;
    delete simicolonSingleAst3;
}

void JumpStatement2::Dump(int depth) {
    TreeRender::push("JumpStatement");
    continueAst1->Dump(depth + 1);
    simicolonSingleAst2->Dump(depth + 1);
    TreeRender::pop();
}

JumpStatement2::~JumpStatement2() {
    delete continueAst1;
    delete simicolonSingleAst2;
}

void JumpStatement3::Dump(int depth) {
    TreeRender::push("JumpStatement");
    breakAst1->Dump(depth + 1);
    simicolonSingleAst2->Dump(depth + 1);
    TreeRender::pop();
}

JumpStatement3::~JumpStatement3() {
    delete breakAst1;
    delete simicolonSingleAst2;
}

void JumpStatement4::Dump(int depth) {
    TreeRender::push("JumpStatement");
    returnAst1->Dump(depth + 1);
    simicolonSingleAst2->Dump(depth + 1);
    TreeRender::pop();
}

JumpStatement4::~JumpStatement4() {
    delete returnAst1;
    delete simicolonSingleAst2;
}

void JumpStatement5::Dump(int depth) {
    TreeRender::push("JumpStatement");
    returnAst1->Dump(depth + 1);
    expressionAst2->Dump(depth + 1);
    simicolonSingleAst3->Dump(depth + 1);
    TreeRender::pop();
}

JumpStatement5::~JumpStatement5() {
    delete returnAst1;
    delete expressionAst2;
    delete simicolonSingleAst3;
}
