// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/statement/labeled_statement.h"

void LabeledStatement1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "LabeledStatement1" << std::endl;
    identifierAst1->Dump(depth + 1);
    colonAst2->Dump(depth + 1);
    statementAst3->Dump(depth + 1);
}

LabeledStatement1::~LabeledStatement1() {
    delete identifierAst1;
    delete colonAst2;
    delete statementAst3;
}

void LabeledStatement2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "LabeledStatement2" << std::endl;
    caseAst1->Dump(depth + 1);
    constantExpressionAst2->Dump(depth + 1);
    colonAst3->Dump(depth + 1);
    statementAst4->Dump(depth + 1);
}

LabeledStatement2::~LabeledStatement2() {
    delete caseAst1;
    delete constantExpressionAst2;
    delete colonAst3;
    delete statementAst4;
}

void LabeledStatement3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "LabeledStatement3" << std::endl;
    defaultAst1->Dump(depth + 1);
    colonAst2->Dump(depth + 1);
    statementAst3->Dump(depth + 1);
}

LabeledStatement3::~LabeledStatement3() {
    delete defaultAst1;
    delete colonAst2;
    delete statementAst3;
}
