// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void StatementList1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StatementList1" << std::endl;
    statementAst1->Dump(depth + 1);
}

StatementList1::~StatementList1() {
    delete statementAst1;
}

void StatementList2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "StatementList2" << std::endl;
    statementListAst1->Dump(depth + 1);
    statementAst2->Dump(depth + 1);
}

StatementList2::~StatementList2() {
    delete statementListAst1;
    delete statementAst2;
}
