// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"

void Statement1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Statement1" << std::endl;
    labeledStatementAst1->Dump(depth + 1);
}

Statement1::~Statement1() {
    delete labeledStatementAst1;
}

void Statement2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Statement2" << std::endl;
    compoundStatementAst1->Dump(depth + 1);
}

Statement2::~Statement2() {
    delete compoundStatementAst1;
}

void Statement3::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Statement3" << std::endl;
    expressionStatementAst1->Dump(depth + 1);
}

Statement3::~Statement3() {
    delete expressionStatementAst1;
}

void Statement4::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Statement4" << std::endl;
    selectionStatementAst1->Dump(depth + 1);
}

Statement4::~Statement4() {
    delete selectionStatementAst1;
}

void Statement5::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Statement5" << std::endl;
    iterationStatementAst1->Dump(depth + 1);
}

Statement5::~Statement5() {
    delete iterationStatementAst1;
}

void Statement6::Dump(int depth) {
    std::cout << "[" << depth << "] " << "Statement6" << std::endl;
    jumpStatementAst1->Dump(depth + 1);
}

Statement6::~Statement6() {
    delete jumpStatementAst1;
}
