// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void Statement1::Dump(int depth) {
    TreeRender::push("Statement");
    labeledStatementAst1->Dump(depth + 1);
    TreeRender::pop();
}

Statement1::~Statement1() {
    delete labeledStatementAst1;
}

void Statement2::Dump(int depth) {
    TreeRender::push("Statement");
    compoundStatementAst1->Dump(depth + 1);
    TreeRender::pop();
}

Statement2::~Statement2() {
    delete compoundStatementAst1;
}

void Statement3::Dump(int depth) {
    TreeRender::push("Statement");
    expressionStatementAst1->Dump(depth + 1);
    TreeRender::pop();
}

Statement3::~Statement3() {
    delete expressionStatementAst1;
}

void Statement4::Dump(int depth) {
    TreeRender::push("Statement");
    selectionStatementAst1->Dump(depth + 1);
    TreeRender::pop();
}

Statement4::~Statement4() {
    delete selectionStatementAst1;
}

void Statement5::Dump(int depth) {
    TreeRender::push("Statement");
    iterationStatementAst1->Dump(depth + 1);
    TreeRender::pop();
}

Statement5::~Statement5() {
    delete iterationStatementAst1;
}

void Statement6::Dump(int depth) {
    TreeRender::push("Statement");
    jumpStatementAst1->Dump(depth + 1);
    TreeRender::pop();
}

Statement6::~Statement6() {
    delete jumpStatementAst1;
}
