// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void StatementList1::Dump(int depth) {
    TreeRender::push("StatementList");
    statementAst1->Dump(depth + 1);
    TreeRender::pop();
}

StatementList1::~StatementList1() {
    delete statementAst1;
}

void StatementList2::Dump(int depth) {
    TreeRender::push("StatementList");
    statementListAst1->Dump(depth + 1);
    statementAst2->Dump(depth + 1);
    TreeRender::pop();
}

StatementList2::~StatementList2() {
    delete statementListAst1;
    delete statementAst2;
}
