// Generated by buildSrc/GenerateAST.py
#ifndef _STATEMENT_LIST_H_
#define _STATEMENT_LIST_H_

//#include "ast/ast.h"
class Statement;

class StatementList: public BasicAST {
public:
    virtual ~StatementList() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class StatementList1: public StatementList {
public:
    Statement* statementAst1;

    StatementList1(
        Statement* statementAst1
    ): statementAst1(statementAst1) {}

    virtual ~StatementList1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class StatementList2: public StatementList {
public:
    StatementList* statementListAst1;
    Statement* statementAst2;

    StatementList2(
        StatementList* statementListAst1,
        Statement* statementAst2
    ): statementListAst1(statementListAst1), statementAst2(statementAst2) {}

    virtual ~StatementList2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

#endif // _STATEMENT_LIST_H_
