// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/statement/translation_unit.h"

void TranslationUnit1::Dump(int depth) {
    std::cout << "[" << depth << "] " << "TranslationUnit1" << std::endl;
    externalDeclarationAst1->Dump(depth + 1);
}

TranslationUnit1::~TranslationUnit1() {
    delete externalDeclarationAst1;
}

void TranslationUnit2::Dump(int depth) {
    std::cout << "[" << depth << "] " << "TranslationUnit2" << std::endl;
    translationUnitAst1->Dump(depth + 1);
    externalDeclarationAst2->Dump(depth + 1);
}

TranslationUnit2::~TranslationUnit2() {
    delete translationUnitAst1;
    delete externalDeclarationAst2;
}
