// Generated by buildSrc/GenerateAST.py
#ifndef _TRANSLATION_UNIT_H_
#define _TRANSLATION_UNIT_H_

#include "ast/ast.h"
//#header

class TranslationUnit: public BasicAST {
public:
    virtual ~TranslationUnit() {}
    virtual IRValuePtr GenerateIR(Context& context) { return nullptr; }
    virtual void Dump(int depth) {}
};

class TranslationUnit1: public TranslationUnit {
public:
    ExternalDeclaration* externalDeclarationAst1;

    TranslationUnit1(
        ExternalDeclaration* externalDeclarationAst1
    ): externalDeclarationAst1(externalDeclarationAst1) {}

    virtual ~TranslationUnit1();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};

class TranslationUnit2: public TranslationUnit {
public:
    TranslationUnit* translationUnitAst1;
    ExternalDeclaration* externalDeclarationAst2;

    TranslationUnit2(
        TranslationUnit* translationUnitAst1,
        ExternalDeclaration* externalDeclarationAst2
    ): translationUnitAst1(translationUnitAst1), externalDeclarationAst2(externalDeclarationAst2) {}

    virtual ~TranslationUnit2();
    virtual IRValuePtr GenerateIR(Context& context);
    virtual void Dump(int depth);

};


#else

#ifndef _CLASS_EXTERNALDECLARATION_
#define _CLASS_EXTERNALDECLARATION_
class ExternalDeclaration;
#endif //_CLASS_EXTERNALDECLARATION_

#endif // _TRANSLATION_UNIT_H_
