// Generated by buildSrc/GenerateAST.py
#include <iostream>
#include "ast/ast.h"
#include "ast/render.h"

void TranslationUnit1::Dump(int depth) {
    TreeRender::push("TranslationUnit");
    externalDeclarationAst1->Dump(depth + 1);
    TreeRender::pop();
}

TranslationUnit1::~TranslationUnit1() {
    delete externalDeclarationAst1;
}

void TranslationUnit2::Dump(int depth) {
    TreeRender::push("TranslationUnit");
    translationUnitAst1->Dump(depth + 1);
    externalDeclarationAst2->Dump(depth + 1);
    TreeRender::pop();
}

TranslationUnit2::~TranslationUnit2() {
    delete translationUnitAst1;
    delete externalDeclarationAst2;
}
